# IPCores 
set script_path [ file dirname [ file normalize [ info script ] ] ]
# IPCores 
#  fifo_generator Properties definition 
set ip_name CDC_fifo_1b
create_ip -name fifo_generator -vendor xilinx.com -library ip -module_name ${ip_name}
set_property -dict [list \
  CONFIG.ADDRESS_WIDTH {32} \
  CONFIG.ARUSER_Width {0} \
  CONFIG.AWUSER_Width {0} \
  CONFIG.Add_NGC_Constraint_AXI {false} \
  CONFIG.Almost_Empty_Flag {false} \
  CONFIG.Almost_Full_Flag {false} \
  CONFIG.BUSER_Width {0} \
  CONFIG.CORE_CLK.FREQ_HZ {100000000} \
  CONFIG.C_SELECT_XPM {0} \
  CONFIG.Clock_Enable_Type {Slave_Interface_Clock_Enable} \
  CONFIG.Clock_Type_AXI {Common_Clock} \
  CONFIG.Component_Name {CDC_fifo_1b} \
  CONFIG.DATA_WIDTH {64} \
  CONFIG.Data_Count {false} \
  CONFIG.Data_Count_Width {4} \
  CONFIG.Disable_Timing_Violations {false} \
  CONFIG.Disable_Timing_Violations_AXI {false} \
  CONFIG.Dout_Reset_Value {0} \
  CONFIG.Empty_Threshold_Assert_Value {2} \
  CONFIG.Empty_Threshold_Assert_Value_axis {1022} \
  CONFIG.Empty_Threshold_Assert_Value_rach {1022} \
  CONFIG.Empty_Threshold_Assert_Value_rdch {1022} \
  CONFIG.Empty_Threshold_Assert_Value_wach {1022} \
  CONFIG.Empty_Threshold_Assert_Value_wdch {1022} \
  CONFIG.Empty_Threshold_Assert_Value_wrch {1022} \
  CONFIG.Empty_Threshold_Negate_Value {3} \
  CONFIG.Enable_Common_Overflow {false} \
  CONFIG.Enable_Common_Underflow {false} \
  CONFIG.Enable_Data_Counts_axis {false} \
  CONFIG.Enable_Data_Counts_rach {false} \
  CONFIG.Enable_Data_Counts_rdch {false} \
  CONFIG.Enable_Data_Counts_wach {false} \
  CONFIG.Enable_Data_Counts_wdch {false} \
  CONFIG.Enable_Data_Counts_wrch {false} \
  CONFIG.Enable_ECC {false} \
  CONFIG.Enable_ECC_Type {Hard_ECC} \
  CONFIG.Enable_ECC_axis {false} \
  CONFIG.Enable_ECC_rach {false} \
  CONFIG.Enable_ECC_rdch {false} \
  CONFIG.Enable_ECC_wach {false} \
  CONFIG.Enable_ECC_wdch {false} \
  CONFIG.Enable_ECC_wrch {false} \
  CONFIG.Enable_Reset_Synchronization {true} \
  CONFIG.Enable_Safety_Circuit {false} \
  CONFIG.Enable_TLAST {false} \
  CONFIG.Enable_TREADY {true} \
  CONFIG.FIFO_Application_Type_axis {Data_FIFO} \
  CONFIG.FIFO_Application_Type_rach {Data_FIFO} \
  CONFIG.FIFO_Application_Type_rdch {Data_FIFO} \
  CONFIG.FIFO_Application_Type_wach {Data_FIFO} \
  CONFIG.FIFO_Application_Type_wdch {Data_FIFO} \
  CONFIG.FIFO_Application_Type_wrch {Data_FIFO} \
  CONFIG.FIFO_Implementation_axis {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_rach {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_rdch {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_wach {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_wdch {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_wrch {Common_Clock_Block_RAM} \
  CONFIG.Fifo_Implementation {Independent_Clocks_Distributed_RAM} \
  CONFIG.Full_Flags_Reset_Value {0} \
  CONFIG.Full_Threshold_Assert_Value {13} \
  CONFIG.Full_Threshold_Assert_Value_axis {1023} \
  CONFIG.Full_Threshold_Assert_Value_rach {1023} \
  CONFIG.Full_Threshold_Assert_Value_rdch {1023} \
  CONFIG.Full_Threshold_Assert_Value_wach {1023} \
  CONFIG.Full_Threshold_Assert_Value_wdch {1023} \
  CONFIG.Full_Threshold_Assert_Value_wrch {1023} \
  CONFIG.Full_Threshold_Negate_Value {12} \
  CONFIG.HAS_ACLKEN {false} \
  CONFIG.HAS_TKEEP {false} \
  CONFIG.HAS_TSTRB {false} \
  CONFIG.ID_WIDTH {0} \
  CONFIG.INTERFACE_TYPE {Native} \
  CONFIG.Inject_Dbit_Error {false} \
  CONFIG.Inject_Dbit_Error_axis {false} \
  CONFIG.Inject_Dbit_Error_rach {false} \
  CONFIG.Inject_Dbit_Error_rdch {false} \
  CONFIG.Inject_Dbit_Error_wach {false} \
  CONFIG.Inject_Dbit_Error_wdch {false} \
  CONFIG.Inject_Dbit_Error_wrch {false} \
  CONFIG.Inject_Sbit_Error {false} \
  CONFIG.Inject_Sbit_Error_axis {false} \
  CONFIG.Inject_Sbit_Error_rach {false} \
  CONFIG.Inject_Sbit_Error_rdch {false} \
  CONFIG.Inject_Sbit_Error_wach {false} \
  CONFIG.Inject_Sbit_Error_wdch {false} \
  CONFIG.Inject_Sbit_Error_wrch {false} \
  CONFIG.Input_Data_Width {1} \
  CONFIG.Input_Depth {16} \
  CONFIG.Input_Depth_axis {1024} \
  CONFIG.Input_Depth_rach {16} \
  CONFIG.Input_Depth_rdch {1024} \
  CONFIG.Input_Depth_wach {16} \
  CONFIG.Input_Depth_wdch {1024} \
  CONFIG.Input_Depth_wrch {16} \
  CONFIG.MASTER_ACLK.FREQ_HZ {100000000} \
  CONFIG.Master_interface_Clock_enable_memory_mapped {false} \
  CONFIG.Output_Data_Width {1} \
  CONFIG.Output_Depth {16} \
  CONFIG.Output_Register_Type {Embedded_Reg} \
  CONFIG.Overflow_Flag {false} \
  CONFIG.Overflow_Flag_AXI {false} \
  CONFIG.Overflow_Sense {Active_High} \
  CONFIG.Overflow_Sense_AXI {Active_High} \
  CONFIG.PROTOCOL {AXI4} \
  CONFIG.Performance_Options {Standard_FIFO} \
  CONFIG.Programmable_Empty_Type {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_axis {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_rach {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_rdch {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_wach {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_wdch {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_wrch {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Full_Type {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_axis {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_rach {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_rdch {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_wach {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_wdch {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_wrch {No_Programmable_Full_Threshold} \
  CONFIG.READ_CLK.FREQ_HZ {100000000} \
  CONFIG.READ_WRITE_MODE {READ_WRITE} \
  CONFIG.RUSER_Width {0} \
  CONFIG.Read_Clock_Frequency {1} \
  CONFIG.Read_Data_Count {false} \
  CONFIG.Read_Data_Count_Width {4} \
  CONFIG.Register_Slice_Mode_axis {Fully_Registered} \
  CONFIG.Register_Slice_Mode_rach {Fully_Registered} \
  CONFIG.Register_Slice_Mode_rdch {Fully_Registered} \
  CONFIG.Register_Slice_Mode_wach {Fully_Registered} \
  CONFIG.Register_Slice_Mode_wdch {Fully_Registered} \
  CONFIG.Register_Slice_Mode_wrch {Fully_Registered} \
  CONFIG.Reset_Pin {false} \
  CONFIG.Reset_Type {Asynchronous_Reset} \
  CONFIG.SLAVE_ACLK.FREQ_HZ {100000000} \
  CONFIG.Slave_interface_Clock_enable_memory_mapped {false} \
  CONFIG.TDATA_NUM_BYTES {1} \
  CONFIG.TDEST_WIDTH {0} \
  CONFIG.TID_WIDTH {0} \
  CONFIG.TKEEP_WIDTH {1} \
  CONFIG.TSTRB_WIDTH {1} \
  CONFIG.TUSER_WIDTH {4} \
  CONFIG.Underflow_Flag {false} \
  CONFIG.Underflow_Flag_AXI {false} \
  CONFIG.Underflow_Sense {Active_High} \
  CONFIG.Underflow_Sense_AXI {Active_High} \
  CONFIG.Use_Dout_Reset {false} \
  CONFIG.Use_Embedded_Registers {false} \
  CONFIG.Use_Embedded_Registers_axis {false} \
  CONFIG.Use_Extra_Logic {false} \
  CONFIG.Valid_Flag {true} \
  CONFIG.Valid_Sense {Active_High} \
  CONFIG.WRITE_CLK.FREQ_HZ {100000000} \
  CONFIG.WUSER_Width {0} \
  CONFIG.Write_Acknowledge_Flag {false} \
  CONFIG.Write_Acknowledge_Sense {Active_High} \
  CONFIG.Write_Clock_Frequency {1} \
  CONFIG.Write_Data_Count {false} \
  CONFIG.Write_Data_Count_Width {4} \
  CONFIG.asymmetric_port_width {false} \
  CONFIG.axis_type {FIFO} \
  CONFIG.dynamic_power_saving {false} \
  CONFIG.ecc_pipeline_reg {false} \
  CONFIG.enable_low_latency {false} \
  CONFIG.enable_read_pointer_increment_by2 {false} \
  CONFIG.rach_type {FIFO} \
  CONFIG.rdch_type {FIFO} \
  CONFIG.synchronization_stages {4} \
  CONFIG.synchronization_stages_axi {2} \
  CONFIG.use_dout_register {false} \
  CONFIG.wach_type {FIFO} \
  CONFIG.wdch_type {FIFO} \
  CONFIG.wrch_type {FIFO} \
  ] [get_ips ${ip_name}]
set_property generate_synth_checkpoint 0 [get_files CDC_fifo_1b.xci]
#  fifo_generator  

#  fifo_generator Properties definition 
set ip_name CDC_fifo_32b
create_ip -name fifo_generator -vendor xilinx.com -library ip -module_name ${ip_name}
set_property -dict [list \
  CONFIG.ADDRESS_WIDTH {32} \
  CONFIG.ARUSER_Width {0} \
  CONFIG.AWUSER_Width {0} \
  CONFIG.Add_NGC_Constraint_AXI {false} \
  CONFIG.Almost_Empty_Flag {false} \
  CONFIG.Almost_Full_Flag {false} \
  CONFIG.BUSER_Width {0} \
  CONFIG.CORE_CLK.FREQ_HZ {100000000} \
  CONFIG.C_SELECT_XPM {0} \
  CONFIG.Clock_Enable_Type {Slave_Interface_Clock_Enable} \
  CONFIG.Clock_Type_AXI {Common_Clock} \
  CONFIG.Component_Name {CDC_fifo_32b} \
  CONFIG.DATA_WIDTH {64} \
  CONFIG.Data_Count {false} \
  CONFIG.Data_Count_Width {4} \
  CONFIG.Disable_Timing_Violations {false} \
  CONFIG.Disable_Timing_Violations_AXI {false} \
  CONFIG.Dout_Reset_Value {0} \
  CONFIG.Empty_Threshold_Assert_Value {2} \
  CONFIG.Empty_Threshold_Assert_Value_axis {1022} \
  CONFIG.Empty_Threshold_Assert_Value_rach {1022} \
  CONFIG.Empty_Threshold_Assert_Value_rdch {1022} \
  CONFIG.Empty_Threshold_Assert_Value_wach {1022} \
  CONFIG.Empty_Threshold_Assert_Value_wdch {1022} \
  CONFIG.Empty_Threshold_Assert_Value_wrch {1022} \
  CONFIG.Empty_Threshold_Negate_Value {3} \
  CONFIG.Enable_Common_Overflow {false} \
  CONFIG.Enable_Common_Underflow {false} \
  CONFIG.Enable_Data_Counts_axis {false} \
  CONFIG.Enable_Data_Counts_rach {false} \
  CONFIG.Enable_Data_Counts_rdch {false} \
  CONFIG.Enable_Data_Counts_wach {false} \
  CONFIG.Enable_Data_Counts_wdch {false} \
  CONFIG.Enable_Data_Counts_wrch {false} \
  CONFIG.Enable_ECC {false} \
  CONFIG.Enable_ECC_Type {Hard_ECC} \
  CONFIG.Enable_ECC_axis {false} \
  CONFIG.Enable_ECC_rach {false} \
  CONFIG.Enable_ECC_rdch {false} \
  CONFIG.Enable_ECC_wach {false} \
  CONFIG.Enable_ECC_wdch {false} \
  CONFIG.Enable_ECC_wrch {false} \
  CONFIG.Enable_Reset_Synchronization {true} \
  CONFIG.Enable_Safety_Circuit {false} \
  CONFIG.Enable_TLAST {false} \
  CONFIG.Enable_TREADY {true} \
  CONFIG.FIFO_Application_Type_axis {Data_FIFO} \
  CONFIG.FIFO_Application_Type_rach {Data_FIFO} \
  CONFIG.FIFO_Application_Type_rdch {Data_FIFO} \
  CONFIG.FIFO_Application_Type_wach {Data_FIFO} \
  CONFIG.FIFO_Application_Type_wdch {Data_FIFO} \
  CONFIG.FIFO_Application_Type_wrch {Data_FIFO} \
  CONFIG.FIFO_Implementation_axis {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_rach {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_rdch {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_wach {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_wdch {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_wrch {Common_Clock_Block_RAM} \
  CONFIG.Fifo_Implementation {Independent_Clocks_Distributed_RAM} \
  CONFIG.Full_Flags_Reset_Value {0} \
  CONFIG.Full_Threshold_Assert_Value {13} \
  CONFIG.Full_Threshold_Assert_Value_axis {1023} \
  CONFIG.Full_Threshold_Assert_Value_rach {1023} \
  CONFIG.Full_Threshold_Assert_Value_rdch {1023} \
  CONFIG.Full_Threshold_Assert_Value_wach {1023} \
  CONFIG.Full_Threshold_Assert_Value_wdch {1023} \
  CONFIG.Full_Threshold_Assert_Value_wrch {1023} \
  CONFIG.Full_Threshold_Negate_Value {12} \
  CONFIG.HAS_ACLKEN {false} \
  CONFIG.HAS_TKEEP {false} \
  CONFIG.HAS_TSTRB {false} \
  CONFIG.ID_WIDTH {0} \
  CONFIG.INTERFACE_TYPE {Native} \
  CONFIG.Inject_Dbit_Error {false} \
  CONFIG.Inject_Dbit_Error_axis {false} \
  CONFIG.Inject_Dbit_Error_rach {false} \
  CONFIG.Inject_Dbit_Error_rdch {false} \
  CONFIG.Inject_Dbit_Error_wach {false} \
  CONFIG.Inject_Dbit_Error_wdch {false} \
  CONFIG.Inject_Dbit_Error_wrch {false} \
  CONFIG.Inject_Sbit_Error {false} \
  CONFIG.Inject_Sbit_Error_axis {false} \
  CONFIG.Inject_Sbit_Error_rach {false} \
  CONFIG.Inject_Sbit_Error_rdch {false} \
  CONFIG.Inject_Sbit_Error_wach {false} \
  CONFIG.Inject_Sbit_Error_wdch {false} \
  CONFIG.Inject_Sbit_Error_wrch {false} \
  CONFIG.Input_Data_Width {32} \
  CONFIG.Input_Depth {16} \
  CONFIG.Input_Depth_axis {1024} \
  CONFIG.Input_Depth_rach {16} \
  CONFIG.Input_Depth_rdch {1024} \
  CONFIG.Input_Depth_wach {16} \
  CONFIG.Input_Depth_wdch {1024} \
  CONFIG.Input_Depth_wrch {16} \
  CONFIG.MASTER_ACLK.FREQ_HZ {100000000} \
  CONFIG.Master_interface_Clock_enable_memory_mapped {false} \
  CONFIG.Output_Data_Width {32} \
  CONFIG.Output_Depth {16} \
  CONFIG.Output_Register_Type {Embedded_Reg} \
  CONFIG.Overflow_Flag {false} \
  CONFIG.Overflow_Flag_AXI {false} \
  CONFIG.Overflow_Sense {Active_High} \
  CONFIG.Overflow_Sense_AXI {Active_High} \
  CONFIG.PROTOCOL {AXI4} \
  CONFIG.Performance_Options {Standard_FIFO} \
  CONFIG.Programmable_Empty_Type {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_axis {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_rach {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_rdch {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_wach {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_wdch {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_wrch {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Full_Type {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_axis {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_rach {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_rdch {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_wach {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_wdch {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_wrch {No_Programmable_Full_Threshold} \
  CONFIG.READ_CLK.FREQ_HZ {100000000} \
  CONFIG.READ_WRITE_MODE {READ_WRITE} \
  CONFIG.RUSER_Width {0} \
  CONFIG.Read_Clock_Frequency {1} \
  CONFIG.Read_Data_Count {false} \
  CONFIG.Read_Data_Count_Width {4} \
  CONFIG.Register_Slice_Mode_axis {Fully_Registered} \
  CONFIG.Register_Slice_Mode_rach {Fully_Registered} \
  CONFIG.Register_Slice_Mode_rdch {Fully_Registered} \
  CONFIG.Register_Slice_Mode_wach {Fully_Registered} \
  CONFIG.Register_Slice_Mode_wdch {Fully_Registered} \
  CONFIG.Register_Slice_Mode_wrch {Fully_Registered} \
  CONFIG.Reset_Pin {false} \
  CONFIG.Reset_Type {Asynchronous_Reset} \
  CONFIG.SLAVE_ACLK.FREQ_HZ {100000000} \
  CONFIG.Slave_interface_Clock_enable_memory_mapped {false} \
  CONFIG.TDATA_NUM_BYTES {1} \
  CONFIG.TDEST_WIDTH {0} \
  CONFIG.TID_WIDTH {0} \
  CONFIG.TKEEP_WIDTH {1} \
  CONFIG.TSTRB_WIDTH {1} \
  CONFIG.TUSER_WIDTH {4} \
  CONFIG.Underflow_Flag {false} \
  CONFIG.Underflow_Flag_AXI {false} \
  CONFIG.Underflow_Sense {Active_High} \
  CONFIG.Underflow_Sense_AXI {Active_High} \
  CONFIG.Use_Dout_Reset {false} \
  CONFIG.Use_Embedded_Registers {false} \
  CONFIG.Use_Embedded_Registers_axis {false} \
  CONFIG.Use_Extra_Logic {false} \
  CONFIG.Valid_Flag {true} \
  CONFIG.Valid_Sense {Active_High} \
  CONFIG.WRITE_CLK.FREQ_HZ {100000000} \
  CONFIG.WUSER_Width {0} \
  CONFIG.Write_Acknowledge_Flag {false} \
  CONFIG.Write_Acknowledge_Sense {Active_High} \
  CONFIG.Write_Clock_Frequency {1} \
  CONFIG.Write_Data_Count {false} \
  CONFIG.Write_Data_Count_Width {4} \
  CONFIG.asymmetric_port_width {false} \
  CONFIG.axis_type {FIFO} \
  CONFIG.dynamic_power_saving {false} \
  CONFIG.ecc_pipeline_reg {false} \
  CONFIG.enable_low_latency {false} \
  CONFIG.enable_read_pointer_increment_by2 {false} \
  CONFIG.rach_type {FIFO} \
  CONFIG.rdch_type {FIFO} \
  CONFIG.synchronization_stages {4} \
  CONFIG.synchronization_stages_axi {2} \
  CONFIG.use_dout_register {false} \
  CONFIG.wach_type {FIFO} \
  CONFIG.wdch_type {FIFO} \
  CONFIG.wrch_type {FIFO} \
  ] [get_ips ${ip_name}]
set_property generate_synth_checkpoint 0 [get_files CDC_fifo_32b.xci]
#  fifo_generator  