# IPCores 
set script_path [ file dirname [ file normalize [ info script ] ] ]
#  fifo_generator Properties definition 
set ip_name CDC_fifo_16b
create_ip -name fifo_generator -vendor xilinx.com -library ip -module_name ${ip_name}
set_property -dict [list \
  CONFIG.ADDRESS_WIDTH {32} \
  CONFIG.ARUSER_Width {0} \
  CONFIG.AWUSER_Width {0} \
  CONFIG.Add_NGC_Constraint_AXI {false} \
  CONFIG.Almost_Empty_Flag {false} \
  CONFIG.Almost_Full_Flag {false} \
  CONFIG.BUSER_Width {0} \
  CONFIG.CORE_CLK.FREQ_HZ {100000000} \
  CONFIG.C_SELECT_XPM {0} \
  CONFIG.Clock_Enable_Type {Slave_Interface_Clock_Enable} \
  CONFIG.Clock_Type_AXI {Common_Clock} \
  CONFIG.Component_Name {CDC_fifo_16b} \
  CONFIG.DATA_WIDTH {64} \
  CONFIG.Data_Count {false} \
  CONFIG.Data_Count_Width {4} \
  CONFIG.Disable_Timing_Violations {false} \
  CONFIG.Disable_Timing_Violations_AXI {false} \
  CONFIG.Dout_Reset_Value {0} \
  CONFIG.Empty_Threshold_Assert_Value {2} \
  CONFIG.Empty_Threshold_Assert_Value_axis {1022} \
  CONFIG.Empty_Threshold_Assert_Value_rach {1022} \
  CONFIG.Empty_Threshold_Assert_Value_rdch {1022} \
  CONFIG.Empty_Threshold_Assert_Value_wach {1022} \
  CONFIG.Empty_Threshold_Assert_Value_wdch {1022} \
  CONFIG.Empty_Threshold_Assert_Value_wrch {1022} \
  CONFIG.Empty_Threshold_Negate_Value {3} \
  CONFIG.Enable_Common_Overflow {false} \
  CONFIG.Enable_Common_Underflow {false} \
  CONFIG.Enable_Data_Counts_axis {false} \
  CONFIG.Enable_Data_Counts_rach {false} \
  CONFIG.Enable_Data_Counts_rdch {false} \
  CONFIG.Enable_Data_Counts_wach {false} \
  CONFIG.Enable_Data_Counts_wdch {false} \
  CONFIG.Enable_Data_Counts_wrch {false} \
  CONFIG.Enable_ECC {false} \
  CONFIG.Enable_ECC_Type {Hard_ECC} \
  CONFIG.Enable_ECC_axis {false} \
  CONFIG.Enable_ECC_rach {false} \
  CONFIG.Enable_ECC_rdch {false} \
  CONFIG.Enable_ECC_wach {false} \
  CONFIG.Enable_ECC_wdch {false} \
  CONFIG.Enable_ECC_wrch {false} \
  CONFIG.Enable_Reset_Synchronization {true} \
  CONFIG.Enable_Safety_Circuit {false} \
  CONFIG.Enable_TLAST {false} \
  CONFIG.Enable_TREADY {true} \
  CONFIG.FIFO_Application_Type_axis {Data_FIFO} \
  CONFIG.FIFO_Application_Type_rach {Data_FIFO} \
  CONFIG.FIFO_Application_Type_rdch {Data_FIFO} \
  CONFIG.FIFO_Application_Type_wach {Data_FIFO} \
  CONFIG.FIFO_Application_Type_wdch {Data_FIFO} \
  CONFIG.FIFO_Application_Type_wrch {Data_FIFO} \
  CONFIG.FIFO_Implementation_axis {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_rach {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_rdch {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_wach {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_wdch {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_wrch {Common_Clock_Block_RAM} \
  CONFIG.Fifo_Implementation {Independent_Clocks_Distributed_RAM} \
  CONFIG.Full_Flags_Reset_Value {0} \
  CONFIG.Full_Threshold_Assert_Value {13} \
  CONFIG.Full_Threshold_Assert_Value_axis {1023} \
  CONFIG.Full_Threshold_Assert_Value_rach {1023} \
  CONFIG.Full_Threshold_Assert_Value_rdch {1023} \
  CONFIG.Full_Threshold_Assert_Value_wach {1023} \
  CONFIG.Full_Threshold_Assert_Value_wdch {1023} \
  CONFIG.Full_Threshold_Assert_Value_wrch {1023} \
  CONFIG.Full_Threshold_Negate_Value {12} \
  CONFIG.HAS_ACLKEN {false} \
  CONFIG.HAS_TKEEP {false} \
  CONFIG.HAS_TSTRB {false} \
  CONFIG.ID_WIDTH {0} \
  CONFIG.INTERFACE_TYPE {Native} \
  CONFIG.Inject_Dbit_Error {false} \
  CONFIG.Inject_Dbit_Error_axis {false} \
  CONFIG.Inject_Dbit_Error_rach {false} \
  CONFIG.Inject_Dbit_Error_rdch {false} \
  CONFIG.Inject_Dbit_Error_wach {false} \
  CONFIG.Inject_Dbit_Error_wdch {false} \
  CONFIG.Inject_Dbit_Error_wrch {false} \
  CONFIG.Inject_Sbit_Error {false} \
  CONFIG.Inject_Sbit_Error_axis {false} \
  CONFIG.Inject_Sbit_Error_rach {false} \
  CONFIG.Inject_Sbit_Error_rdch {false} \
  CONFIG.Inject_Sbit_Error_wach {false} \
  CONFIG.Inject_Sbit_Error_wdch {false} \
  CONFIG.Inject_Sbit_Error_wrch {false} \
  CONFIG.Input_Data_Width {16} \
  CONFIG.Input_Depth {16} \
  CONFIG.Input_Depth_axis {1024} \
  CONFIG.Input_Depth_rach {16} \
  CONFIG.Input_Depth_rdch {1024} \
  CONFIG.Input_Depth_wach {16} \
  CONFIG.Input_Depth_wdch {1024} \
  CONFIG.Input_Depth_wrch {16} \
  CONFIG.MASTER_ACLK.FREQ_HZ {100000000} \
  CONFIG.Master_interface_Clock_enable_memory_mapped {false} \
  CONFIG.Output_Data_Width {16} \
  CONFIG.Output_Depth {16} \
  CONFIG.Output_Register_Type {Embedded_Reg} \
  CONFIG.Overflow_Flag {false} \
  CONFIG.Overflow_Flag_AXI {false} \
  CONFIG.Overflow_Sense {Active_High} \
  CONFIG.Overflow_Sense_AXI {Active_High} \
  CONFIG.PROTOCOL {AXI4} \
  CONFIG.Performance_Options {Standard_FIFO} \
  CONFIG.Programmable_Empty_Type {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_axis {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_rach {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_rdch {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_wach {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_wdch {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_wrch {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Full_Type {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_axis {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_rach {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_rdch {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_wach {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_wdch {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_wrch {No_Programmable_Full_Threshold} \
  CONFIG.READ_CLK.FREQ_HZ {100000000} \
  CONFIG.READ_WRITE_MODE {READ_WRITE} \
  CONFIG.RUSER_Width {0} \
  CONFIG.Read_Clock_Frequency {1} \
  CONFIG.Read_Data_Count {false} \
  CONFIG.Read_Data_Count_Width {4} \
  CONFIG.Register_Slice_Mode_axis {Fully_Registered} \
  CONFIG.Register_Slice_Mode_rach {Fully_Registered} \
  CONFIG.Register_Slice_Mode_rdch {Fully_Registered} \
  CONFIG.Register_Slice_Mode_wach {Fully_Registered} \
  CONFIG.Register_Slice_Mode_wdch {Fully_Registered} \
  CONFIG.Register_Slice_Mode_wrch {Fully_Registered} \
  CONFIG.Reset_Pin {false} \
  CONFIG.Reset_Type {Asynchronous_Reset} \
  CONFIG.SLAVE_ACLK.FREQ_HZ {100000000} \
  CONFIG.Slave_interface_Clock_enable_memory_mapped {false} \
  CONFIG.TDATA_NUM_BYTES {1} \
  CONFIG.TDEST_WIDTH {0} \
  CONFIG.TID_WIDTH {0} \
  CONFIG.TKEEP_WIDTH {1} \
  CONFIG.TSTRB_WIDTH {1} \
  CONFIG.TUSER_WIDTH {4} \
  CONFIG.Underflow_Flag {false} \
  CONFIG.Underflow_Flag_AXI {false} \
  CONFIG.Underflow_Sense {Active_High} \
  CONFIG.Underflow_Sense_AXI {Active_High} \
  CONFIG.Use_Dout_Reset {false} \
  CONFIG.Use_Embedded_Registers {false} \
  CONFIG.Use_Embedded_Registers_axis {false} \
  CONFIG.Use_Extra_Logic {false} \
  CONFIG.Valid_Flag {true} \
  CONFIG.Valid_Sense {Active_High} \
  CONFIG.WRITE_CLK.FREQ_HZ {100000000} \
  CONFIG.WUSER_Width {0} \
  CONFIG.Write_Acknowledge_Flag {false} \
  CONFIG.Write_Acknowledge_Sense {Active_High} \
  CONFIG.Write_Clock_Frequency {1} \
  CONFIG.Write_Data_Count {false} \
  CONFIG.Write_Data_Count_Width {4} \
  CONFIG.asymmetric_port_width {false} \
  CONFIG.axis_type {FIFO} \
  CONFIG.dynamic_power_saving {false} \
  CONFIG.ecc_pipeline_reg {false} \
  CONFIG.enable_low_latency {false} \
  CONFIG.enable_read_pointer_increment_by2 {false} \
  CONFIG.rach_type {FIFO} \
  CONFIG.rdch_type {FIFO} \
  CONFIG.synchronization_stages {4} \
  CONFIG.synchronization_stages_axi {2} \
  CONFIG.use_dout_register {false} \
  CONFIG.wach_type {FIFO} \
  CONFIG.wdch_type {FIFO} \
  CONFIG.wrch_type {FIFO} \
  ] [get_ips ${ip_name}]
set_property generate_synth_checkpoint 0 [get_files CDC_fifo_16b.xci]
#  fifo_generator  

#  fifo_generator Properties definition 
set ip_name CDC_fifo_1b
create_ip -name fifo_generator -vendor xilinx.com -library ip -module_name ${ip_name}
set_property -dict [list \
  CONFIG.ADDRESS_WIDTH {32} \
  CONFIG.ARUSER_Width {0} \
  CONFIG.AWUSER_Width {0} \
  CONFIG.Add_NGC_Constraint_AXI {false} \
  CONFIG.Almost_Empty_Flag {false} \
  CONFIG.Almost_Full_Flag {false} \
  CONFIG.BUSER_Width {0} \
  CONFIG.CORE_CLK.FREQ_HZ {100000000} \
  CONFIG.C_SELECT_XPM {0} \
  CONFIG.Clock_Enable_Type {Slave_Interface_Clock_Enable} \
  CONFIG.Clock_Type_AXI {Common_Clock} \
  CONFIG.Component_Name {CDC_fifo_1b} \
  CONFIG.DATA_WIDTH {64} \
  CONFIG.Data_Count {false} \
  CONFIG.Data_Count_Width {4} \
  CONFIG.Disable_Timing_Violations {false} \
  CONFIG.Disable_Timing_Violations_AXI {false} \
  CONFIG.Dout_Reset_Value {0} \
  CONFIG.Empty_Threshold_Assert_Value {2} \
  CONFIG.Empty_Threshold_Assert_Value_axis {1022} \
  CONFIG.Empty_Threshold_Assert_Value_rach {1022} \
  CONFIG.Empty_Threshold_Assert_Value_rdch {1022} \
  CONFIG.Empty_Threshold_Assert_Value_wach {1022} \
  CONFIG.Empty_Threshold_Assert_Value_wdch {1022} \
  CONFIG.Empty_Threshold_Assert_Value_wrch {1022} \
  CONFIG.Empty_Threshold_Negate_Value {3} \
  CONFIG.Enable_Common_Overflow {false} \
  CONFIG.Enable_Common_Underflow {false} \
  CONFIG.Enable_Data_Counts_axis {false} \
  CONFIG.Enable_Data_Counts_rach {false} \
  CONFIG.Enable_Data_Counts_rdch {false} \
  CONFIG.Enable_Data_Counts_wach {false} \
  CONFIG.Enable_Data_Counts_wdch {false} \
  CONFIG.Enable_Data_Counts_wrch {false} \
  CONFIG.Enable_ECC {false} \
  CONFIG.Enable_ECC_Type {Hard_ECC} \
  CONFIG.Enable_ECC_axis {false} \
  CONFIG.Enable_ECC_rach {false} \
  CONFIG.Enable_ECC_rdch {false} \
  CONFIG.Enable_ECC_wach {false} \
  CONFIG.Enable_ECC_wdch {false} \
  CONFIG.Enable_ECC_wrch {false} \
  CONFIG.Enable_Reset_Synchronization {true} \
  CONFIG.Enable_Safety_Circuit {false} \
  CONFIG.Enable_TLAST {false} \
  CONFIG.Enable_TREADY {true} \
  CONFIG.FIFO_Application_Type_axis {Data_FIFO} \
  CONFIG.FIFO_Application_Type_rach {Data_FIFO} \
  CONFIG.FIFO_Application_Type_rdch {Data_FIFO} \
  CONFIG.FIFO_Application_Type_wach {Data_FIFO} \
  CONFIG.FIFO_Application_Type_wdch {Data_FIFO} \
  CONFIG.FIFO_Application_Type_wrch {Data_FIFO} \
  CONFIG.FIFO_Implementation_axis {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_rach {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_rdch {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_wach {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_wdch {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_wrch {Common_Clock_Block_RAM} \
  CONFIG.Fifo_Implementation {Independent_Clocks_Distributed_RAM} \
  CONFIG.Full_Flags_Reset_Value {0} \
  CONFIG.Full_Threshold_Assert_Value {13} \
  CONFIG.Full_Threshold_Assert_Value_axis {1023} \
  CONFIG.Full_Threshold_Assert_Value_rach {1023} \
  CONFIG.Full_Threshold_Assert_Value_rdch {1023} \
  CONFIG.Full_Threshold_Assert_Value_wach {1023} \
  CONFIG.Full_Threshold_Assert_Value_wdch {1023} \
  CONFIG.Full_Threshold_Assert_Value_wrch {1023} \
  CONFIG.Full_Threshold_Negate_Value {12} \
  CONFIG.HAS_ACLKEN {false} \
  CONFIG.HAS_TKEEP {false} \
  CONFIG.HAS_TSTRB {false} \
  CONFIG.ID_WIDTH {0} \
  CONFIG.INTERFACE_TYPE {Native} \
  CONFIG.Inject_Dbit_Error {false} \
  CONFIG.Inject_Dbit_Error_axis {false} \
  CONFIG.Inject_Dbit_Error_rach {false} \
  CONFIG.Inject_Dbit_Error_rdch {false} \
  CONFIG.Inject_Dbit_Error_wach {false} \
  CONFIG.Inject_Dbit_Error_wdch {false} \
  CONFIG.Inject_Dbit_Error_wrch {false} \
  CONFIG.Inject_Sbit_Error {false} \
  CONFIG.Inject_Sbit_Error_axis {false} \
  CONFIG.Inject_Sbit_Error_rach {false} \
  CONFIG.Inject_Sbit_Error_rdch {false} \
  CONFIG.Inject_Sbit_Error_wach {false} \
  CONFIG.Inject_Sbit_Error_wdch {false} \
  CONFIG.Inject_Sbit_Error_wrch {false} \
  CONFIG.Input_Data_Width {1} \
  CONFIG.Input_Depth {16} \
  CONFIG.Input_Depth_axis {1024} \
  CONFIG.Input_Depth_rach {16} \
  CONFIG.Input_Depth_rdch {1024} \
  CONFIG.Input_Depth_wach {16} \
  CONFIG.Input_Depth_wdch {1024} \
  CONFIG.Input_Depth_wrch {16} \
  CONFIG.MASTER_ACLK.FREQ_HZ {100000000} \
  CONFIG.Master_interface_Clock_enable_memory_mapped {false} \
  CONFIG.Output_Data_Width {1} \
  CONFIG.Output_Depth {16} \
  CONFIG.Output_Register_Type {Embedded_Reg} \
  CONFIG.Overflow_Flag {false} \
  CONFIG.Overflow_Flag_AXI {false} \
  CONFIG.Overflow_Sense {Active_High} \
  CONFIG.Overflow_Sense_AXI {Active_High} \
  CONFIG.PROTOCOL {AXI4} \
  CONFIG.Performance_Options {Standard_FIFO} \
  CONFIG.Programmable_Empty_Type {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_axis {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_rach {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_rdch {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_wach {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_wdch {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_wrch {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Full_Type {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_axis {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_rach {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_rdch {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_wach {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_wdch {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_wrch {No_Programmable_Full_Threshold} \
  CONFIG.READ_CLK.FREQ_HZ {100000000} \
  CONFIG.READ_WRITE_MODE {READ_WRITE} \
  CONFIG.RUSER_Width {0} \
  CONFIG.Read_Clock_Frequency {1} \
  CONFIG.Read_Data_Count {false} \
  CONFIG.Read_Data_Count_Width {4} \
  CONFIG.Register_Slice_Mode_axis {Fully_Registered} \
  CONFIG.Register_Slice_Mode_rach {Fully_Registered} \
  CONFIG.Register_Slice_Mode_rdch {Fully_Registered} \
  CONFIG.Register_Slice_Mode_wach {Fully_Registered} \
  CONFIG.Register_Slice_Mode_wdch {Fully_Registered} \
  CONFIG.Register_Slice_Mode_wrch {Fully_Registered} \
  CONFIG.Reset_Pin {false} \
  CONFIG.Reset_Type {Asynchronous_Reset} \
  CONFIG.SLAVE_ACLK.FREQ_HZ {100000000} \
  CONFIG.Slave_interface_Clock_enable_memory_mapped {false} \
  CONFIG.TDATA_NUM_BYTES {1} \
  CONFIG.TDEST_WIDTH {0} \
  CONFIG.TID_WIDTH {0} \
  CONFIG.TKEEP_WIDTH {1} \
  CONFIG.TSTRB_WIDTH {1} \
  CONFIG.TUSER_WIDTH {4} \
  CONFIG.Underflow_Flag {false} \
  CONFIG.Underflow_Flag_AXI {false} \
  CONFIG.Underflow_Sense {Active_High} \
  CONFIG.Underflow_Sense_AXI {Active_High} \
  CONFIG.Use_Dout_Reset {false} \
  CONFIG.Use_Embedded_Registers {false} \
  CONFIG.Use_Embedded_Registers_axis {false} \
  CONFIG.Use_Extra_Logic {false} \
  CONFIG.Valid_Flag {true} \
  CONFIG.Valid_Sense {Active_High} \
  CONFIG.WRITE_CLK.FREQ_HZ {100000000} \
  CONFIG.WUSER_Width {0} \
  CONFIG.Write_Acknowledge_Flag {false} \
  CONFIG.Write_Acknowledge_Sense {Active_High} \
  CONFIG.Write_Clock_Frequency {1} \
  CONFIG.Write_Data_Count {false} \
  CONFIG.Write_Data_Count_Width {4} \
  CONFIG.asymmetric_port_width {false} \
  CONFIG.axis_type {FIFO} \
  CONFIG.dynamic_power_saving {false} \
  CONFIG.ecc_pipeline_reg {false} \
  CONFIG.enable_low_latency {false} \
  CONFIG.enable_read_pointer_increment_by2 {false} \
  CONFIG.rach_type {FIFO} \
  CONFIG.rdch_type {FIFO} \
  CONFIG.synchronization_stages {4} \
  CONFIG.synchronization_stages_axi {2} \
  CONFIG.use_dout_register {false} \
  CONFIG.wach_type {FIFO} \
  CONFIG.wdch_type {FIFO} \
  CONFIG.wrch_type {FIFO} \
  ] [get_ips ${ip_name}]
set_property generate_synth_checkpoint 0 [get_files CDC_fifo_1b.xci]
#  fifo_generator  

#  fifo_generator Properties definition 
set ip_name CDC_fifo_3b
create_ip -name fifo_generator -vendor xilinx.com -library ip -module_name ${ip_name}
set_property -dict [list \
  CONFIG.ADDRESS_WIDTH {32} \
  CONFIG.ARUSER_Width {0} \
  CONFIG.AWUSER_Width {0} \
  CONFIG.Add_NGC_Constraint_AXI {false} \
  CONFIG.Almost_Empty_Flag {false} \
  CONFIG.Almost_Full_Flag {false} \
  CONFIG.BUSER_Width {0} \
  CONFIG.CORE_CLK.FREQ_HZ {100000000} \
  CONFIG.C_SELECT_XPM {0} \
  CONFIG.Clock_Enable_Type {Slave_Interface_Clock_Enable} \
  CONFIG.Clock_Type_AXI {Common_Clock} \
  CONFIG.Component_Name {CDC_fifo_3b} \
  CONFIG.DATA_WIDTH {64} \
  CONFIG.Data_Count {false} \
  CONFIG.Data_Count_Width {4} \
  CONFIG.Disable_Timing_Violations {false} \
  CONFIG.Disable_Timing_Violations_AXI {false} \
  CONFIG.Dout_Reset_Value {0} \
  CONFIG.Empty_Threshold_Assert_Value {2} \
  CONFIG.Empty_Threshold_Assert_Value_axis {1022} \
  CONFIG.Empty_Threshold_Assert_Value_rach {1022} \
  CONFIG.Empty_Threshold_Assert_Value_rdch {1022} \
  CONFIG.Empty_Threshold_Assert_Value_wach {1022} \
  CONFIG.Empty_Threshold_Assert_Value_wdch {1022} \
  CONFIG.Empty_Threshold_Assert_Value_wrch {1022} \
  CONFIG.Empty_Threshold_Negate_Value {3} \
  CONFIG.Enable_Common_Overflow {false} \
  CONFIG.Enable_Common_Underflow {false} \
  CONFIG.Enable_Data_Counts_axis {false} \
  CONFIG.Enable_Data_Counts_rach {false} \
  CONFIG.Enable_Data_Counts_rdch {false} \
  CONFIG.Enable_Data_Counts_wach {false} \
  CONFIG.Enable_Data_Counts_wdch {false} \
  CONFIG.Enable_Data_Counts_wrch {false} \
  CONFIG.Enable_ECC {false} \
  CONFIG.Enable_ECC_Type {Hard_ECC} \
  CONFIG.Enable_ECC_axis {false} \
  CONFIG.Enable_ECC_rach {false} \
  CONFIG.Enable_ECC_rdch {false} \
  CONFIG.Enable_ECC_wach {false} \
  CONFIG.Enable_ECC_wdch {false} \
  CONFIG.Enable_ECC_wrch {false} \
  CONFIG.Enable_Reset_Synchronization {true} \
  CONFIG.Enable_Safety_Circuit {false} \
  CONFIG.Enable_TLAST {false} \
  CONFIG.Enable_TREADY {true} \
  CONFIG.FIFO_Application_Type_axis {Data_FIFO} \
  CONFIG.FIFO_Application_Type_rach {Data_FIFO} \
  CONFIG.FIFO_Application_Type_rdch {Data_FIFO} \
  CONFIG.FIFO_Application_Type_wach {Data_FIFO} \
  CONFIG.FIFO_Application_Type_wdch {Data_FIFO} \
  CONFIG.FIFO_Application_Type_wrch {Data_FIFO} \
  CONFIG.FIFO_Implementation_axis {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_rach {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_rdch {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_wach {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_wdch {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_wrch {Common_Clock_Block_RAM} \
  CONFIG.Fifo_Implementation {Independent_Clocks_Distributed_RAM} \
  CONFIG.Full_Flags_Reset_Value {0} \
  CONFIG.Full_Threshold_Assert_Value {13} \
  CONFIG.Full_Threshold_Assert_Value_axis {1023} \
  CONFIG.Full_Threshold_Assert_Value_rach {1023} \
  CONFIG.Full_Threshold_Assert_Value_rdch {1023} \
  CONFIG.Full_Threshold_Assert_Value_wach {1023} \
  CONFIG.Full_Threshold_Assert_Value_wdch {1023} \
  CONFIG.Full_Threshold_Assert_Value_wrch {1023} \
  CONFIG.Full_Threshold_Negate_Value {12} \
  CONFIG.HAS_ACLKEN {false} \
  CONFIG.HAS_TKEEP {false} \
  CONFIG.HAS_TSTRB {false} \
  CONFIG.ID_WIDTH {0} \
  CONFIG.INTERFACE_TYPE {Native} \
  CONFIG.Inject_Dbit_Error {false} \
  CONFIG.Inject_Dbit_Error_axis {false} \
  CONFIG.Inject_Dbit_Error_rach {false} \
  CONFIG.Inject_Dbit_Error_rdch {false} \
  CONFIG.Inject_Dbit_Error_wach {false} \
  CONFIG.Inject_Dbit_Error_wdch {false} \
  CONFIG.Inject_Dbit_Error_wrch {false} \
  CONFIG.Inject_Sbit_Error {false} \
  CONFIG.Inject_Sbit_Error_axis {false} \
  CONFIG.Inject_Sbit_Error_rach {false} \
  CONFIG.Inject_Sbit_Error_rdch {false} \
  CONFIG.Inject_Sbit_Error_wach {false} \
  CONFIG.Inject_Sbit_Error_wdch {false} \
  CONFIG.Inject_Sbit_Error_wrch {false} \
  CONFIG.Input_Data_Width {3} \
  CONFIG.Input_Depth {16} \
  CONFIG.Input_Depth_axis {1024} \
  CONFIG.Input_Depth_rach {16} \
  CONFIG.Input_Depth_rdch {1024} \
  CONFIG.Input_Depth_wach {16} \
  CONFIG.Input_Depth_wdch {1024} \
  CONFIG.Input_Depth_wrch {16} \
  CONFIG.MASTER_ACLK.FREQ_HZ {100000000} \
  CONFIG.Master_interface_Clock_enable_memory_mapped {false} \
  CONFIG.Output_Data_Width {3} \
  CONFIG.Output_Depth {16} \
  CONFIG.Output_Register_Type {Embedded_Reg} \
  CONFIG.Overflow_Flag {false} \
  CONFIG.Overflow_Flag_AXI {false} \
  CONFIG.Overflow_Sense {Active_High} \
  CONFIG.Overflow_Sense_AXI {Active_High} \
  CONFIG.PROTOCOL {AXI4} \
  CONFIG.Performance_Options {Standard_FIFO} \
  CONFIG.Programmable_Empty_Type {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_axis {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_rach {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_rdch {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_wach {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_wdch {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_wrch {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Full_Type {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_axis {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_rach {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_rdch {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_wach {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_wdch {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_wrch {No_Programmable_Full_Threshold} \
  CONFIG.READ_CLK.FREQ_HZ {100000000} \
  CONFIG.READ_WRITE_MODE {READ_WRITE} \
  CONFIG.RUSER_Width {0} \
  CONFIG.Read_Clock_Frequency {1} \
  CONFIG.Read_Data_Count {false} \
  CONFIG.Read_Data_Count_Width {4} \
  CONFIG.Register_Slice_Mode_axis {Fully_Registered} \
  CONFIG.Register_Slice_Mode_rach {Fully_Registered} \
  CONFIG.Register_Slice_Mode_rdch {Fully_Registered} \
  CONFIG.Register_Slice_Mode_wach {Fully_Registered} \
  CONFIG.Register_Slice_Mode_wdch {Fully_Registered} \
  CONFIG.Register_Slice_Mode_wrch {Fully_Registered} \
  CONFIG.Reset_Pin {false} \
  CONFIG.Reset_Type {Asynchronous_Reset} \
  CONFIG.SLAVE_ACLK.FREQ_HZ {100000000} \
  CONFIG.Slave_interface_Clock_enable_memory_mapped {false} \
  CONFIG.TDATA_NUM_BYTES {1} \
  CONFIG.TDEST_WIDTH {0} \
  CONFIG.TID_WIDTH {0} \
  CONFIG.TKEEP_WIDTH {1} \
  CONFIG.TSTRB_WIDTH {1} \
  CONFIG.TUSER_WIDTH {4} \
  CONFIG.Underflow_Flag {false} \
  CONFIG.Underflow_Flag_AXI {false} \
  CONFIG.Underflow_Sense {Active_High} \
  CONFIG.Underflow_Sense_AXI {Active_High} \
  CONFIG.Use_Dout_Reset {false} \
  CONFIG.Use_Embedded_Registers {false} \
  CONFIG.Use_Embedded_Registers_axis {false} \
  CONFIG.Use_Extra_Logic {false} \
  CONFIG.Valid_Flag {true} \
  CONFIG.Valid_Sense {Active_High} \
  CONFIG.WRITE_CLK.FREQ_HZ {100000000} \
  CONFIG.WUSER_Width {0} \
  CONFIG.Write_Acknowledge_Flag {false} \
  CONFIG.Write_Acknowledge_Sense {Active_High} \
  CONFIG.Write_Clock_Frequency {1} \
  CONFIG.Write_Data_Count {false} \
  CONFIG.Write_Data_Count_Width {4} \
  CONFIG.asymmetric_port_width {false} \
  CONFIG.axis_type {FIFO} \
  CONFIG.dynamic_power_saving {false} \
  CONFIG.ecc_pipeline_reg {false} \
  CONFIG.enable_low_latency {false} \
  CONFIG.enable_read_pointer_increment_by2 {false} \
  CONFIG.rach_type {FIFO} \
  CONFIG.rdch_type {FIFO} \
  CONFIG.synchronization_stages {4} \
  CONFIG.synchronization_stages_axi {2} \
  CONFIG.use_dout_register {false} \
  CONFIG.wach_type {FIFO} \
  CONFIG.wdch_type {FIFO} \
  CONFIG.wrch_type {FIFO} \
  ] [get_ips ${ip_name}]
set_property generate_synth_checkpoint 0 [get_files CDC_fifo_3b.xci]
#  fifo_generator  

#  fir_compiler Properties definition 
set ip_name dac_interpolation_1536msps_to_3072msps
create_ip -name fir_compiler -vendor xilinx.com -library ip -module_name ${ip_name}
set_property -dict [list \
  CONFIG.ACLK_INTF.FREQ_HZ {100000000} \
  CONFIG.BestPrecision {false} \
  CONFIG.Blank_Output {false} \
  CONFIG.Channel_Sequence {Basic} \
  CONFIG.Clock_Frequency {245.76} \
  CONFIG.CoefficientSource {COE_File} \
  CONFIG.CoefficientVector {6,0,-4,-3,5,6,-6,-13,7,44,64,44,7,-13,-6,6,5,-3,-4,0,6} \
  CONFIG.Coefficient_Buffer_Type {Automatic} \
  CONFIG.Coefficient_File $script_path/../../RTL_code/coe_files/rfdc_dac_data_interp_and_pack/interpolation_2x_PRB.coe \
  CONFIG.Coefficient_Fractional_Bits {0} \
  CONFIG.Coefficient_Reload {false} \
  CONFIG.Coefficient_Sets {1} \
  CONFIG.Coefficient_Sign {Signed} \
  CONFIG.Coefficient_Structure {Inferred} \
  CONFIG.Coefficient_Width {16} \
  CONFIG.ColumnConfig {2} \
  CONFIG.Component_Name {dac_interpolation_1536msps_to_3072msps} \
  CONFIG.DATA_Has_TLAST {Not_Required} \
  CONFIG.DATA_TUSER_Width {1} \
  CONFIG.Data_Buffer_Type {Automatic} \
  CONFIG.Data_Fractional_Bits {0} \
  CONFIG.Data_Sign {Signed} \
  CONFIG.Data_Width {16} \
  CONFIG.Decimation_Rate {1} \
  CONFIG.DisplayReloadOrder {false} \
  CONFIG.Filter_Architecture {Systolic_Multiply_Accumulate} \
  CONFIG.Filter_Selection {1} \
  CONFIG.Filter_Type {Interpolation} \
  CONFIG.GUI_Behaviour {Coregen} \
  CONFIG.Gen_MIF_Files {false} \
  CONFIG.Gen_MIF_from_COE {false} \
  CONFIG.Gen_MIF_from_Spec {false} \
  CONFIG.HardwareOversamplingRate {1} \
  CONFIG.Has_ACLKEN {false} \
  CONFIG.Has_ARESETn {true} \
  CONFIG.Input_Buffer_Type {Automatic} \
  CONFIG.Inter_Column_Pipe_Length {4} \
  CONFIG.Interpolation_Rate {2} \
  CONFIG.M_DATA_Has_TREADY {false} \
  CONFIG.M_DATA_Has_TUSER {Not_Required} \
  CONFIG.Multi_Column_Support {Automatic} \
  CONFIG.Num_Reload_Slots {1} \
  CONFIG.Number_Channels {1} \
  CONFIG.Number_Paths {1} \
  CONFIG.Optimization_Goal {Area} \
  CONFIG.Optimization_List {None} \
  CONFIG.Optimization_Selection {None} \
  CONFIG.Output_Buffer_Type {Automatic} \
  CONFIG.Output_Rounding_Mode {Full_Precision} \
  CONFIG.Output_Width {31} \
  CONFIG.Passband_Max {0.5} \
  CONFIG.Passband_Min {0.0} \
  CONFIG.Pattern_List {P4-0,P4-1,P4-2,P4-3,P4-4} \
  CONFIG.Preference_For_Other_Storage {Automatic} \
  CONFIG.Quantization {Integer_Coefficients} \
  CONFIG.RateSpecification {Frequency_Specification} \
  CONFIG.Rate_Change_Type {Integer} \
  CONFIG.Reload_File {no_coe_file_loaded} \
  CONFIG.Reset_Data_Vector {true} \
  CONFIG.S_CONFIG_Method {Single} \
  CONFIG.S_CONFIG_Sync_Mode {On_Vector} \
  CONFIG.S_DATA_Has_FIFO {true} \
  CONFIG.S_DATA_Has_TUSER {Not_Required} \
  CONFIG.SamplePeriod {1} \
  CONFIG.Sample_Frequency {15.36} \
  CONFIG.Select_Pattern {All} \
  CONFIG.Stopband_Max {1.0} \
  CONFIG.Stopband_Min {0.5} \
  CONFIG.Zero_Pack_Factor {1} \
  ] [get_ips ${ip_name}]
set_property generate_synth_checkpoint 0 [get_files dac_interpolation_1536msps_to_3072msps.xci]
#  fir_compiler  

#  fir_compiler Properties definition 
set ip_name dac_interpolation_192msps_to_384msps
create_ip -name fir_compiler -vendor xilinx.com -library ip -module_name ${ip_name}
set_property -dict [list \
  CONFIG.ACLK_INTF.FREQ_HZ {100000000} \
  CONFIG.BestPrecision {false} \
  CONFIG.Blank_Output {false} \
  CONFIG.Channel_Sequence {Basic} \
  CONFIG.Clock_Frequency {245.76} \
  CONFIG.CoefficientSource {COE_File} \
  CONFIG.CoefficientVector {6,0,-4,-3,5,6,-6,-13,7,44,64,44,7,-13,-6,6,5,-3,-4,0,6} \
  CONFIG.Coefficient_Buffer_Type {Automatic} \
  CONFIG.Coefficient_File $script_path/../../RTL_code/coe_files/rfdc_dac_data_interp_and_pack/interpolation_2x_PRB.coe \
  CONFIG.Coefficient_Fractional_Bits {0} \
  CONFIG.Coefficient_Reload {false} \
  CONFIG.Coefficient_Sets {1} \
  CONFIG.Coefficient_Sign {Signed} \
  CONFIG.Coefficient_Structure {Inferred} \
  CONFIG.Coefficient_Width {16} \
  CONFIG.ColumnConfig {1} \
  CONFIG.Component_Name {dac_interpolation_192msps_to_384msps} \
  CONFIG.DATA_Has_TLAST {Not_Required} \
  CONFIG.DATA_TUSER_Width {1} \
  CONFIG.Data_Buffer_Type {Automatic} \
  CONFIG.Data_Fractional_Bits {0} \
  CONFIG.Data_Sign {Signed} \
  CONFIG.Data_Width {16} \
  CONFIG.Decimation_Rate {1} \
  CONFIG.DisplayReloadOrder {false} \
  CONFIG.Filter_Architecture {Systolic_Multiply_Accumulate} \
  CONFIG.Filter_Selection {1} \
  CONFIG.Filter_Type {Interpolation} \
  CONFIG.GUI_Behaviour {Coregen} \
  CONFIG.Gen_MIF_Files {false} \
  CONFIG.Gen_MIF_from_COE {false} \
  CONFIG.Gen_MIF_from_Spec {false} \
  CONFIG.HardwareOversamplingRate {1} \
  CONFIG.Has_ACLKEN {false} \
  CONFIG.Has_ARESETn {true} \
  CONFIG.Input_Buffer_Type {Automatic} \
  CONFIG.Inter_Column_Pipe_Length {4} \
  CONFIG.Interpolation_Rate {2} \
  CONFIG.M_DATA_Has_TREADY {false} \
  CONFIG.M_DATA_Has_TUSER {Not_Required} \
  CONFIG.Multi_Column_Support {Automatic} \
  CONFIG.Num_Reload_Slots {1} \
  CONFIG.Number_Channels {1} \
  CONFIG.Number_Paths {1} \
  CONFIG.Optimization_Goal {Area} \
  CONFIG.Optimization_List {None} \
  CONFIG.Optimization_Selection {None} \
  CONFIG.Output_Buffer_Type {Automatic} \
  CONFIG.Output_Rounding_Mode {Full_Precision} \
  CONFIG.Output_Width {31} \
  CONFIG.Passband_Max {0.5} \
  CONFIG.Passband_Min {0.0} \
  CONFIG.Pattern_List {P4-0,P4-1,P4-2,P4-3,P4-4} \
  CONFIG.Preference_For_Other_Storage {Automatic} \
  CONFIG.Quantization {Integer_Coefficients} \
  CONFIG.RateSpecification {Frequency_Specification} \
  CONFIG.Rate_Change_Type {Integer} \
  CONFIG.Reload_File {no_coe_file_loaded} \
  CONFIG.Reset_Data_Vector {true} \
  CONFIG.S_CONFIG_Method {Single} \
  CONFIG.S_CONFIG_Sync_Mode {On_Vector} \
  CONFIG.S_DATA_Has_FIFO {true} \
  CONFIG.S_DATA_Has_TUSER {Not_Required} \
  CONFIG.SamplePeriod {1} \
  CONFIG.Sample_Frequency {1.92} \
  CONFIG.Select_Pattern {All} \
  CONFIG.Stopband_Max {1.0} \
  CONFIG.Stopband_Min {0.5} \
  CONFIG.Zero_Pack_Factor {1} \
  ] [get_ips ${ip_name}]
set_property generate_synth_checkpoint 0 [get_files dac_interpolation_192msps_to_384msps.xci]
#  fir_compiler  

#  fir_compiler Properties definition 
set ip_name dac_interpolation_3072msps_to_24576msps
create_ip -name fir_compiler -vendor xilinx.com -library ip -module_name ${ip_name}
set_property -dict [list \
  CONFIG.ACLK_INTF.FREQ_HZ {100000000} \
  CONFIG.BestPrecision {false} \
  CONFIG.Blank_Output {false} \
  CONFIG.Channel_Sequence {Basic} \
  CONFIG.Clock_Frequency {245.76} \
  CONFIG.CoefficientSource {COE_File} \
  CONFIG.CoefficientVector {6,0,-4,-3,5,6,-6,-13,7,44,64,44,7,-13,-6,6,5,-3,-4,0,6} \
  CONFIG.Coefficient_Buffer_Type {Automatic} \
  CONFIG.Coefficient_File $script_path/../../RTL_code/coe_files/rfdc_dac_data_interp_and_pack/interpolation_8x_PRB.coe \
  CONFIG.Coefficient_Fractional_Bits {0} \
  CONFIG.Coefficient_Reload {false} \
  CONFIG.Coefficient_Sets {1} \
  CONFIG.Coefficient_Sign {Signed} \
  CONFIG.Coefficient_Structure {Inferred} \
  CONFIG.Coefficient_Width {16} \
  CONFIG.ColumnConfig {16} \
  CONFIG.Component_Name {dac_interpolation_3072msps_to_24576msps} \
  CONFIG.DATA_Has_TLAST {Not_Required} \
  CONFIG.DATA_TUSER_Width {1} \
  CONFIG.Data_Buffer_Type {Automatic} \
  CONFIG.Data_Fractional_Bits {0} \
  CONFIG.Data_Sign {Signed} \
  CONFIG.Data_Width {16} \
  CONFIG.Decimation_Rate {1} \
  CONFIG.DisplayReloadOrder {false} \
  CONFIG.Filter_Architecture {Systolic_Multiply_Accumulate} \
  CONFIG.Filter_Selection {1} \
  CONFIG.Filter_Type {Interpolation} \
  CONFIG.GUI_Behaviour {Coregen} \
  CONFIG.Gen_MIF_Files {false} \
  CONFIG.Gen_MIF_from_COE {false} \
  CONFIG.Gen_MIF_from_Spec {false} \
  CONFIG.HardwareOversamplingRate {1} \
  CONFIG.Has_ACLKEN {false} \
  CONFIG.Has_ARESETn {true} \
  CONFIG.Input_Buffer_Type {Automatic} \
  CONFIG.Inter_Column_Pipe_Length {4} \
  CONFIG.Interpolation_Rate {8} \
  CONFIG.M_DATA_Has_TREADY {false} \
  CONFIG.M_DATA_Has_TUSER {Not_Required} \
  CONFIG.Multi_Column_Support {Automatic} \
  CONFIG.Num_Reload_Slots {1} \
  CONFIG.Number_Channels {1} \
  CONFIG.Number_Paths {1} \
  CONFIG.Optimization_Goal {Area} \
  CONFIG.Optimization_List {None} \
  CONFIG.Optimization_Selection {None} \
  CONFIG.Output_Buffer_Type {Automatic} \
  CONFIG.Output_Rounding_Mode {Full_Precision} \
  CONFIG.Output_Width {31} \
  CONFIG.Passband_Max {0.5} \
  CONFIG.Passband_Min {0.0} \
  CONFIG.Pattern_List {P4-0,P4-1,P4-2,P4-3,P4-4} \
  CONFIG.Preference_For_Other_Storage {Automatic} \
  CONFIG.Quantization {Integer_Coefficients} \
  CONFIG.RateSpecification {Frequency_Specification} \
  CONFIG.Rate_Change_Type {Integer} \
  CONFIG.Reload_File {no_coe_file_loaded} \
  CONFIG.Reset_Data_Vector {true} \
  CONFIG.S_CONFIG_Method {Single} \
  CONFIG.S_CONFIG_Sync_Mode {On_Vector} \
  CONFIG.S_DATA_Has_FIFO {true} \
  CONFIG.S_DATA_Has_TUSER {Not_Required} \
  CONFIG.SamplePeriod {1} \
  CONFIG.Sample_Frequency {30.72} \
  CONFIG.Select_Pattern {All} \
  CONFIG.Stopband_Max {1.0} \
  CONFIG.Stopband_Min {0.5} \
  CONFIG.Zero_Pack_Factor {1} \
  ] [get_ips ${ip_name}]
set_property generate_synth_checkpoint 0 [get_files dac_interpolation_3072msps_to_24576msps.xci]
#  fir_compiler  

#  fir_compiler Properties definition 
set ip_name dac_interpolation_384msps_to_768msps
create_ip -name fir_compiler -vendor xilinx.com -library ip -module_name ${ip_name}
set_property -dict [list \
  CONFIG.ACLK_INTF.FREQ_HZ {100000000} \
  CONFIG.BestPrecision {false} \
  CONFIG.Blank_Output {false} \
  CONFIG.Channel_Sequence {Basic} \
  CONFIG.Clock_Frequency {245.76} \
  CONFIG.CoefficientSource {COE_File} \
  CONFIG.CoefficientVector {6,0,-4,-3,5,6,-6,-13,7,44,64,44,7,-13,-6,6,5,-3,-4,0,6} \
  CONFIG.Coefficient_Buffer_Type {Automatic} \
  CONFIG.Coefficient_File $script_path/../../RTL_code/coe_files/rfdc_dac_data_interp_and_pack/interpolation_2x_PRB.coe \
  CONFIG.Coefficient_Fractional_Bits {0} \
  CONFIG.Coefficient_Reload {false} \
  CONFIG.Coefficient_Sets {1} \
  CONFIG.Coefficient_Sign {Signed} \
  CONFIG.Coefficient_Structure {Inferred} \
  CONFIG.Coefficient_Width {16} \
  CONFIG.ColumnConfig {1} \
  CONFIG.Component_Name {dac_interpolation_384msps_to_768msps} \
  CONFIG.DATA_Has_TLAST {Not_Required} \
  CONFIG.DATA_TUSER_Width {1} \
  CONFIG.Data_Buffer_Type {Automatic} \
  CONFIG.Data_Fractional_Bits {0} \
  CONFIG.Data_Sign {Signed} \
  CONFIG.Data_Width {16} \
  CONFIG.Decimation_Rate {1} \
  CONFIG.DisplayReloadOrder {false} \
  CONFIG.Filter_Architecture {Systolic_Multiply_Accumulate} \
  CONFIG.Filter_Selection {1} \
  CONFIG.Filter_Type {Interpolation} \
  CONFIG.GUI_Behaviour {Coregen} \
  CONFIG.Gen_MIF_Files {false} \
  CONFIG.Gen_MIF_from_COE {false} \
  CONFIG.Gen_MIF_from_Spec {false} \
  CONFIG.HardwareOversamplingRate {1} \
  CONFIG.Has_ACLKEN {false} \
  CONFIG.Has_ARESETn {true} \
  CONFIG.Input_Buffer_Type {Automatic} \
  CONFIG.Inter_Column_Pipe_Length {4} \
  CONFIG.Interpolation_Rate {2} \
  CONFIG.M_DATA_Has_TREADY {false} \
  CONFIG.M_DATA_Has_TUSER {Not_Required} \
  CONFIG.Multi_Column_Support {Automatic} \
  CONFIG.Num_Reload_Slots {1} \
  CONFIG.Number_Channels {1} \
  CONFIG.Number_Paths {1} \
  CONFIG.Optimization_Goal {Area} \
  CONFIG.Optimization_List {None} \
  CONFIG.Optimization_Selection {None} \
  CONFIG.Output_Buffer_Type {Automatic} \
  CONFIG.Output_Rounding_Mode {Full_Precision} \
  CONFIG.Output_Width {31} \
  CONFIG.Passband_Max {0.5} \
  CONFIG.Passband_Min {0.0} \
  CONFIG.Pattern_List {P4-0,P4-1,P4-2,P4-3,P4-4} \
  CONFIG.Preference_For_Other_Storage {Automatic} \
  CONFIG.Quantization {Integer_Coefficients} \
  CONFIG.RateSpecification {Frequency_Specification} \
  CONFIG.Rate_Change_Type {Integer} \
  CONFIG.Reload_File {no_coe_file_loaded} \
  CONFIG.Reset_Data_Vector {true} \
  CONFIG.S_CONFIG_Method {Single} \
  CONFIG.S_CONFIG_Sync_Mode {On_Vector} \
  CONFIG.S_DATA_Has_FIFO {true} \
  CONFIG.S_DATA_Has_TUSER {Not_Required} \
  CONFIG.SamplePeriod {1} \
  CONFIG.Sample_Frequency {3.84} \
  CONFIG.Select_Pattern {All} \
  CONFIG.Stopband_Max {1.0} \
  CONFIG.Stopband_Min {0.5} \
  CONFIG.Zero_Pack_Factor {1} \
  ] [get_ips ${ip_name}]
set_property generate_synth_checkpoint 0 [get_files dac_interpolation_384msps_to_768msps.xci]
#  fir_compiler  

#  fir_compiler Properties definition 
set ip_name dac_interpolation_768msps_to_1536msps
create_ip -name fir_compiler -vendor xilinx.com -library ip -module_name ${ip_name}
set_property -dict [list \
  CONFIG.ACLK_INTF.FREQ_HZ {100000000} \
  CONFIG.BestPrecision {false} \
  CONFIG.Blank_Output {false} \
  CONFIG.Channel_Sequence {Basic} \
  CONFIG.Clock_Frequency {245.76} \
  CONFIG.CoefficientSource {COE_File} \
  CONFIG.CoefficientVector {6,0,-4,-3,5,6,-6,-13,7,44,64,44,7,-13,-6,6,5,-3,-4,0,6} \
  CONFIG.Coefficient_Buffer_Type {Automatic} \
  CONFIG.Coefficient_File $script_path/../../RTL_code/coe_files/rfdc_dac_data_interp_and_pack/interpolation_2x_PRB.coe \
  CONFIG.Coefficient_Fractional_Bits {0} \
  CONFIG.Coefficient_Reload {false} \
  CONFIG.Coefficient_Sets {1} \
  CONFIG.Coefficient_Sign {Signed} \
  CONFIG.Coefficient_Structure {Inferred} \
  CONFIG.Coefficient_Width {16} \
  CONFIG.ColumnConfig {1} \
  CONFIG.Component_Name {dac_interpolation_768msps_to_1536msps} \
  CONFIG.DATA_Has_TLAST {Not_Required} \
  CONFIG.DATA_TUSER_Width {1} \
  CONFIG.Data_Buffer_Type {Automatic} \
  CONFIG.Data_Fractional_Bits {0} \
  CONFIG.Data_Sign {Signed} \
  CONFIG.Data_Width {16} \
  CONFIG.Decimation_Rate {1} \
  CONFIG.DisplayReloadOrder {false} \
  CONFIG.Filter_Architecture {Systolic_Multiply_Accumulate} \
  CONFIG.Filter_Selection {1} \
  CONFIG.Filter_Type {Interpolation} \
  CONFIG.GUI_Behaviour {Coregen} \
  CONFIG.Gen_MIF_Files {false} \
  CONFIG.Gen_MIF_from_COE {false} \
  CONFIG.Gen_MIF_from_Spec {false} \
  CONFIG.HardwareOversamplingRate {1} \
  CONFIG.Has_ACLKEN {false} \
  CONFIG.Has_ARESETn {true} \
  CONFIG.Input_Buffer_Type {Automatic} \
  CONFIG.Inter_Column_Pipe_Length {4} \
  CONFIG.Interpolation_Rate {2} \
  CONFIG.M_DATA_Has_TREADY {false} \
  CONFIG.M_DATA_Has_TUSER {Not_Required} \
  CONFIG.Multi_Column_Support {Automatic} \
  CONFIG.Num_Reload_Slots {1} \
  CONFIG.Number_Channels {1} \
  CONFIG.Number_Paths {1} \
  CONFIG.Optimization_Goal {Area} \
  CONFIG.Optimization_List {None} \
  CONFIG.Optimization_Selection {None} \
  CONFIG.Output_Buffer_Type {Automatic} \
  CONFIG.Output_Rounding_Mode {Full_Precision} \
  CONFIG.Output_Width {31} \
  CONFIG.Passband_Max {0.5} \
  CONFIG.Passband_Min {0.0} \
  CONFIG.Pattern_List {P4-0,P4-1,P4-2,P4-3,P4-4} \
  CONFIG.Preference_For_Other_Storage {Automatic} \
  CONFIG.Quantization {Integer_Coefficients} \
  CONFIG.RateSpecification {Frequency_Specification} \
  CONFIG.Rate_Change_Type {Integer} \
  CONFIG.Reload_File {no_coe_file_loaded} \
  CONFIG.Reset_Data_Vector {true} \
  CONFIG.S_CONFIG_Method {Single} \
  CONFIG.S_CONFIG_Sync_Mode {On_Vector} \
  CONFIG.S_DATA_Has_FIFO {true} \
  CONFIG.S_DATA_Has_TUSER {Not_Required} \
  CONFIG.SamplePeriod {1} \
  CONFIG.Sample_Frequency {7.68} \
  CONFIG.Select_Pattern {All} \
  CONFIG.Stopband_Max {1.0} \
  CONFIG.Stopband_Min {0.5} \
  CONFIG.Zero_Pack_Factor {1} \
  ] [get_ips ${ip_name}]
set_property generate_synth_checkpoint 0 [get_files dac_interpolation_768msps_to_1536msps.xci]
#  fir_compiler  

#  c_shift_ram Properties definition 
set ip_name lat_leveller_shift_reg_1536msps
create_ip -name c_shift_ram -vendor xilinx.com -library ip -module_name ${ip_name}
set_property -dict [list \
  CONFIG.AsyncInitRadix {2} \
  CONFIG.AsyncInitVal {00000000000000000} \
  CONFIG.CE {false} \
  CONFIG.CEPriority {Sync_Overrides_CE} \
  CONFIG.CLK_INTF.FREQ_HZ {100000000} \
  CONFIG.Component_Name {lat_leveller_shift_reg_1536msps} \
  CONFIG.DefaultData {00000000000000000} \
  CONFIG.DefaultDataRadix {2} \
  CONFIG.Depth {6} \
  CONFIG.MemInitFile {no_coe_file_loaded} \
  CONFIG.OptGoal {Resources} \
  CONFIG.ReadMifFile {false} \
  CONFIG.RegLastBit {true} \
  CONFIG.SCLR {false} \
  CONFIG.SINIT {false} \
  CONFIG.SSET {false} \
  CONFIG.ShiftRegType {Fixed_Length} \
  CONFIG.SyncCtrlPriority {Reset_Overrides_Set} \
  CONFIG.SyncInitRadix {2} \
  CONFIG.SyncInitVal {00000000000000000} \
  CONFIG.Width {17} \
  ] [get_ips ${ip_name}]
set_property generate_synth_checkpoint 0 [get_files lat_leveller_shift_reg_1536msps.xci]
#  c_shift_ram  

#  c_shift_ram Properties definition 
set ip_name lat_leveller_shift_reg_192msps
create_ip -name c_shift_ram -vendor xilinx.com -library ip -module_name ${ip_name}
set_property -dict [list \
  CONFIG.AsyncInitRadix {2} \
  CONFIG.AsyncInitVal {00000000000000000} \
  CONFIG.CE {false} \
  CONFIG.CEPriority {Sync_Overrides_CE} \
  CONFIG.CLK_INTF.FREQ_HZ {100000000} \
  CONFIG.Component_Name {lat_leveller_shift_reg_192msps} \
  CONFIG.DefaultData {00000000000000000} \
  CONFIG.DefaultDataRadix {2} \
  CONFIG.Depth {19} \
  CONFIG.MemInitFile {no_coe_file_loaded} \
  CONFIG.OptGoal {Resources} \
  CONFIG.ReadMifFile {false} \
  CONFIG.RegLastBit {true} \
  CONFIG.SCLR {false} \
  CONFIG.SINIT {false} \
  CONFIG.SSET {false} \
  CONFIG.ShiftRegType {Fixed_Length} \
  CONFIG.SyncCtrlPriority {Reset_Overrides_Set} \
  CONFIG.SyncInitRadix {2} \
  CONFIG.SyncInitVal {00000000000000000} \
  CONFIG.Width {17} \
  ] [get_ips ${ip_name}]
set_property generate_synth_checkpoint 0 [get_files lat_leveller_shift_reg_192msps.xci]
#  c_shift_ram  

#  c_shift_ram Properties definition 
set ip_name lat_leveller_shift_reg_3072msps
create_ip -name c_shift_ram -vendor xilinx.com -library ip -module_name ${ip_name}
set_property -dict [list \
  CONFIG.AsyncInitRadix {2} \
  CONFIG.AsyncInitVal {00000000000000000} \
  CONFIG.CE {false} \
  CONFIG.CEPriority {Sync_Overrides_CE} \
  CONFIG.CLK_INTF.FREQ_HZ {100000000} \
  CONFIG.Component_Name {lat_leveller_shift_reg_3072msps} \
  CONFIG.DefaultData {00000000000000000} \
  CONFIG.DefaultDataRadix {2} \
  CONFIG.Depth {12} \
  CONFIG.MemInitFile {no_coe_file_loaded} \
  CONFIG.OptGoal {Resources} \
  CONFIG.ReadMifFile {false} \
  CONFIG.RegLastBit {true} \
  CONFIG.SCLR {false} \
  CONFIG.SINIT {false} \
  CONFIG.SSET {false} \
  CONFIG.ShiftRegType {Fixed_Length} \
  CONFIG.SyncCtrlPriority {Reset_Overrides_Set} \
  CONFIG.SyncInitRadix {2} \
  CONFIG.SyncInitVal {00000000000000000} \
  CONFIG.Width {17} \
  ] [get_ips ${ip_name}]
set_property generate_synth_checkpoint 0 [get_files lat_leveller_shift_reg_3072msps.xci]
#  c_shift_ram  

#  c_shift_ram Properties definition 
set ip_name lat_leveller_shift_reg_384msps
create_ip -name c_shift_ram -vendor xilinx.com -library ip -module_name ${ip_name}
set_property -dict [list \
  CONFIG.AsyncInitRadix {2} \
  CONFIG.AsyncInitVal {00000000000000000} \
  CONFIG.CE {false} \
  CONFIG.CEPriority {Sync_Overrides_CE} \
  CONFIG.CLK_INTF.FREQ_HZ {100000000} \
  CONFIG.Component_Name {lat_leveller_shift_reg_384msps} \
  CONFIG.DefaultData {00000000000000000} \
  CONFIG.DefaultDataRadix {2} \
  CONFIG.Depth {5} \
  CONFIG.MemInitFile {no_coe_file_loaded} \
  CONFIG.OptGoal {Resources} \
  CONFIG.ReadMifFile {false} \
  CONFIG.RegLastBit {true} \
  CONFIG.SCLR {false} \
  CONFIG.SINIT {false} \
  CONFIG.SSET {false} \
  CONFIG.ShiftRegType {Fixed_Length} \
  CONFIG.SyncCtrlPriority {Reset_Overrides_Set} \
  CONFIG.SyncInitRadix {2} \
  CONFIG.SyncInitVal {00000000000000000} \
  CONFIG.Width {17} \
  ] [get_ips ${ip_name}]
set_property generate_synth_checkpoint 0 [get_files lat_leveller_shift_reg_384msps.xci]
#  c_shift_ram  

#  c_shift_ram Properties definition 
set ip_name lat_leveller_shift_reg_768msps
create_ip -name c_shift_ram -vendor xilinx.com -library ip -module_name ${ip_name}
set_property -dict [list \
  CONFIG.AsyncInitRadix {2} \
  CONFIG.AsyncInitVal {00000000000000000} \
  CONFIG.CE {false} \
  CONFIG.CEPriority {Sync_Overrides_CE} \
  CONFIG.CLK_INTF.FREQ_HZ {100000000} \
  CONFIG.Component_Name {lat_leveller_shift_reg_768msps} \
  CONFIG.DefaultData {00000000000000000} \
  CONFIG.DefaultDataRadix {2} \
  CONFIG.Depth {76} \
  CONFIG.MemInitFile {no_coe_file_loaded} \
  CONFIG.OptGoal {Resources} \
  CONFIG.ReadMifFile {false} \
  CONFIG.RegLastBit {true} \
  CONFIG.SCLR {false} \
  CONFIG.SINIT {false} \
  CONFIG.SSET {false} \
  CONFIG.ShiftRegType {Fixed_Length} \
  CONFIG.SyncCtrlPriority {Reset_Overrides_Set} \
  CONFIG.SyncInitRadix {2} \
  CONFIG.SyncInitVal {00000000000000000} \
  CONFIG.Width {17} \
  ] [get_ips ${ip_name}]
set_property generate_synth_checkpoint 0 [get_files lat_leveller_shift_reg_768msps.xci]
#  c_shift_ram  

#  fir_compiler Properties definition 
set ip_name lowpass_clean_signal_at245msps
create_ip -name fir_compiler -vendor xilinx.com -library ip -module_name ${ip_name}
set_property -dict [list \
  CONFIG.ACLK_INTF.FREQ_HZ {100000000} \
  CONFIG.BestPrecision {false} \
  CONFIG.Blank_Output {false} \
  CONFIG.Channel_Sequence {Basic} \
  CONFIG.Clock_Frequency {245.76} \
  CONFIG.CoefficientSource {COE_File} \
  CONFIG.CoefficientVector {6,0,-4,-3,5,6,-6,-13,7,44,64,44,7,-13,-6,6,5,-3,-4,0,6} \
  CONFIG.Coefficient_Buffer_Type {Automatic} \
  CONFIG.Coefficient_File $script_path/../../RTL_code/coe_files/rfdc_dac_data_interp_and_pack/lowpass_clean_signal_at245msps.coe \
  CONFIG.Coefficient_Fractional_Bits {0} \
  CONFIG.Coefficient_Reload {false} \
  CONFIG.Coefficient_Sets {1} \
  CONFIG.Coefficient_Sign {Signed} \
  CONFIG.Coefficient_Structure {Inferred} \
  CONFIG.Coefficient_Width {16} \
  CONFIG.ColumnConfig {63} \
  CONFIG.Component_Name {lowpass_clean_signal_at245msps} \
  CONFIG.DATA_Has_TLAST {Not_Required} \
  CONFIG.DATA_TUSER_Width {1} \
  CONFIG.Data_Buffer_Type {Automatic} \
  CONFIG.Data_Fractional_Bits {0} \
  CONFIG.Data_Sign {Signed} \
  CONFIG.Data_Width {16} \
  CONFIG.Decimation_Rate {1} \
  CONFIG.DisplayReloadOrder {false} \
  CONFIG.Filter_Architecture {Systolic_Multiply_Accumulate} \
  CONFIG.Filter_Selection {1} \
  CONFIG.Filter_Type {Single_Rate} \
  CONFIG.GUI_Behaviour {Coregen} \
  CONFIG.Gen_MIF_Files {false} \
  CONFIG.Gen_MIF_from_COE {false} \
  CONFIG.Gen_MIF_from_Spec {false} \
  CONFIG.HardwareOversamplingRate {1} \
  CONFIG.Has_ACLKEN {false} \
  CONFIG.Has_ARESETn {true} \
  CONFIG.Input_Buffer_Type {Automatic} \
  CONFIG.Inter_Column_Pipe_Length {4} \
  CONFIG.Interpolation_Rate {1} \
  CONFIG.M_DATA_Has_TREADY {false} \
  CONFIG.M_DATA_Has_TUSER {Not_Required} \
  CONFIG.Multi_Column_Support {Automatic} \
  CONFIG.Num_Reload_Slots {1} \
  CONFIG.Number_Channels {1} \
  CONFIG.Number_Paths {1} \
  CONFIG.Optimization_Goal {Area} \
  CONFIG.Optimization_List {None} \
  CONFIG.Optimization_Selection {None} \
  CONFIG.Output_Buffer_Type {Automatic} \
  CONFIG.Output_Rounding_Mode {Full_Precision} \
  CONFIG.Output_Width {35} \
  CONFIG.Passband_Max {0.5} \
  CONFIG.Passband_Min {0.0} \
  CONFIG.Pattern_List {P4-0,P4-1,P4-2,P4-3,P4-4} \
  CONFIG.Preference_For_Other_Storage {Automatic} \
  CONFIG.Quantization {Integer_Coefficients} \
  CONFIG.RateSpecification {Frequency_Specification} \
  CONFIG.Rate_Change_Type {Integer} \
  CONFIG.Reload_File {no_coe_file_loaded} \
  CONFIG.Reset_Data_Vector {true} \
  CONFIG.S_CONFIG_Method {Single} \
  CONFIG.S_CONFIG_Sync_Mode {On_Vector} \
  CONFIG.S_DATA_Has_FIFO {true} \
  CONFIG.S_DATA_Has_TUSER {Not_Required} \
  CONFIG.SamplePeriod {1} \
  CONFIG.Sample_Frequency {245.76} \
  CONFIG.Select_Pattern {All} \
  CONFIG.Stopband_Max {1.0} \
  CONFIG.Stopband_Min {0.5} \
  CONFIG.Zero_Pack_Factor {1} \
  ] [get_ips ${ip_name}]
set_property generate_synth_checkpoint 0 [get_files lowpass_clean_signal_at245msps.xci]
#  fir_compiler  
