set_property widget {hexEdit} [ipgui::get_guiparamspec -name "G_BUILD_TIME" -component [ipx::current_core] ]
set_property value 0x00000000 [ipx::get_user_parameters G_BUILD_TIME -of_objects [ipx::current_core]]
set_property value 0x00000000 [ipx::get_hdl_parameters G_BUILD_TIME -of_objects [ipx::current_core]]
set_property value_bit_string_length 32 [ipx::get_user_parameters G_BUILD_TIME -of_objects [ipx::current_core]]
set_property value_bit_string_length 32 [ipx::get_hdl_parameters G_BUILD_TIME -of_objects [ipx::current_core]]
set_property value_format bitString [ipx::get_user_parameters G_BUILD_TIME -of_objects [ipx::current_core]]
set_property value_format bitString [ipx::get_hdl_parameters G_BUILD_TIME -of_objects [ipx::current_core]]
set_property widget {hexEdit} [ipgui::get_guiparamspec -name "G_BUILD_DATE" -component [ipx::current_core] ]
set_property value 0x00000000 [ipx::get_user_parameters G_BUILD_DATE -of_objects [ipx::current_core]]
set_property value 0x00000000 [ipx::get_hdl_parameters G_BUILD_DATE -of_objects [ipx::current_core]]
set_property value_bit_string_length 32 [ipx::get_user_parameters G_BUILD_DATE -of_objects [ipx::current_core]]
set_property value_bit_string_length 32 [ipx::get_hdl_parameters G_BUILD_DATE -of_objects [ipx::current_core]]
set_property value_format bitString [ipx::get_user_parameters G_BUILD_DATE -of_objects [ipx::current_core]]
set_property value_format bitString [ipx::get_hdl_parameters G_BUILD_DATE -of_objects [ipx::current_core]]
set_property widget {hexEdit} [ipgui::get_guiparamspec -name "G_BUILD_COMMIT_HASH" -component [ipx::current_core] ]
set_property value 0x00000000 [ipx::get_user_parameters G_BUILD_COMMIT_HASH -of_objects [ipx::current_core]]
set_property value 0x00000000 [ipx::get_hdl_parameters G_BUILD_COMMIT_HASH -of_objects [ipx::current_core]]
set_property value_bit_string_length 32 [ipx::get_user_parameters G_BUILD_COMMIT_HASH -of_objects [ipx::current_core]]
set_property value_bit_string_length 32 [ipx::get_hdl_parameters G_BUILD_COMMIT_HASH -of_objects [ipx::current_core]]
set_property value_format bitString [ipx::get_user_parameters G_BUILD_COMMIT_HASH -of_objects [ipx::current_core]]
set_property value_format bitString [ipx::get_hdl_parameters G_BUILD_COMMIT_HASH -of_objects [ipx::current_core]]
