# IPCores 
set script_path [ file dirname [ file normalize [ info script ] ] ]
# IPCores 

#  fifo_generator Properties definition 
set ip_name CDC_fifo_16b
create_ip -name fifo_generator -vendor xilinx.com -library ip -module_name ${ip_name}
set_property -dict [list \
  CONFIG.ADDRESS_WIDTH {32} \
  CONFIG.ARUSER_Width {0} \
  CONFIG.AWUSER_Width {0} \
  CONFIG.Add_NGC_Constraint_AXI {false} \
  CONFIG.Almost_Empty_Flag {false} \
  CONFIG.Almost_Full_Flag {false} \
  CONFIG.BUSER_Width {0} \
  CONFIG.CORE_CLK.FREQ_HZ {100000000} \
  CONFIG.C_SELECT_XPM {0} \
  CONFIG.Clock_Enable_Type {Slave_Interface_Clock_Enable} \
  CONFIG.Clock_Type_AXI {Common_Clock} \
  CONFIG.Component_Name {CDC_fifo_16b} \
  CONFIG.DATA_WIDTH {64} \
  CONFIG.Data_Count {false} \
  CONFIG.Data_Count_Width {4} \
  CONFIG.Disable_Timing_Violations {false} \
  CONFIG.Disable_Timing_Violations_AXI {false} \
  CONFIG.Dout_Reset_Value {0} \
  CONFIG.Empty_Threshold_Assert_Value {2} \
  CONFIG.Empty_Threshold_Assert_Value_axis {1022} \
  CONFIG.Empty_Threshold_Assert_Value_rach {1022} \
  CONFIG.Empty_Threshold_Assert_Value_rdch {1022} \
  CONFIG.Empty_Threshold_Assert_Value_wach {1022} \
  CONFIG.Empty_Threshold_Assert_Value_wdch {1022} \
  CONFIG.Empty_Threshold_Assert_Value_wrch {1022} \
  CONFIG.Empty_Threshold_Negate_Value {3} \
  CONFIG.Enable_Common_Overflow {false} \
  CONFIG.Enable_Common_Underflow {false} \
  CONFIG.Enable_Data_Counts_axis {false} \
  CONFIG.Enable_Data_Counts_rach {false} \
  CONFIG.Enable_Data_Counts_rdch {false} \
  CONFIG.Enable_Data_Counts_wach {false} \
  CONFIG.Enable_Data_Counts_wdch {false} \
  CONFIG.Enable_Data_Counts_wrch {false} \
  CONFIG.Enable_ECC {false} \
  CONFIG.Enable_ECC_Type {Hard_ECC} \
  CONFIG.Enable_ECC_axis {false} \
  CONFIG.Enable_ECC_rach {false} \
  CONFIG.Enable_ECC_rdch {false} \
  CONFIG.Enable_ECC_wach {false} \
  CONFIG.Enable_ECC_wdch {false} \
  CONFIG.Enable_ECC_wrch {false} \
  CONFIG.Enable_Reset_Synchronization {true} \
  CONFIG.Enable_Safety_Circuit {false} \
  CONFIG.Enable_TLAST {false} \
  CONFIG.Enable_TREADY {true} \
  CONFIG.FIFO_Application_Type_axis {Data_FIFO} \
  CONFIG.FIFO_Application_Type_rach {Data_FIFO} \
  CONFIG.FIFO_Application_Type_rdch {Data_FIFO} \
  CONFIG.FIFO_Application_Type_wach {Data_FIFO} \
  CONFIG.FIFO_Application_Type_wdch {Data_FIFO} \
  CONFIG.FIFO_Application_Type_wrch {Data_FIFO} \
  CONFIG.FIFO_Implementation_axis {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_rach {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_rdch {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_wach {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_wdch {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_wrch {Common_Clock_Block_RAM} \
  CONFIG.Fifo_Implementation {Independent_Clocks_Distributed_RAM} \
  CONFIG.Full_Flags_Reset_Value {0} \
  CONFIG.Full_Threshold_Assert_Value {13} \
  CONFIG.Full_Threshold_Assert_Value_axis {1023} \
  CONFIG.Full_Threshold_Assert_Value_rach {1023} \
  CONFIG.Full_Threshold_Assert_Value_rdch {1023} \
  CONFIG.Full_Threshold_Assert_Value_wach {1023} \
  CONFIG.Full_Threshold_Assert_Value_wdch {1023} \
  CONFIG.Full_Threshold_Assert_Value_wrch {1023} \
  CONFIG.Full_Threshold_Negate_Value {12} \
  CONFIG.HAS_ACLKEN {false} \
  CONFIG.HAS_TKEEP {false} \
  CONFIG.HAS_TSTRB {false} \
  CONFIG.ID_WIDTH {0} \
  CONFIG.INTERFACE_TYPE {Native} \
  CONFIG.Inject_Dbit_Error {false} \
  CONFIG.Inject_Dbit_Error_axis {false} \
  CONFIG.Inject_Dbit_Error_rach {false} \
  CONFIG.Inject_Dbit_Error_rdch {false} \
  CONFIG.Inject_Dbit_Error_wach {false} \
  CONFIG.Inject_Dbit_Error_wdch {false} \
  CONFIG.Inject_Dbit_Error_wrch {false} \
  CONFIG.Inject_Sbit_Error {false} \
  CONFIG.Inject_Sbit_Error_axis {false} \
  CONFIG.Inject_Sbit_Error_rach {false} \
  CONFIG.Inject_Sbit_Error_rdch {false} \
  CONFIG.Inject_Sbit_Error_wach {false} \
  CONFIG.Inject_Sbit_Error_wdch {false} \
  CONFIG.Inject_Sbit_Error_wrch {false} \
  CONFIG.Input_Data_Width {16} \
  CONFIG.Input_Depth {16} \
  CONFIG.Input_Depth_axis {1024} \
  CONFIG.Input_Depth_rach {16} \
  CONFIG.Input_Depth_rdch {1024} \
  CONFIG.Input_Depth_wach {16} \
  CONFIG.Input_Depth_wdch {1024} \
  CONFIG.Input_Depth_wrch {16} \
  CONFIG.MASTER_ACLK.FREQ_HZ {100000000} \
  CONFIG.Master_interface_Clock_enable_memory_mapped {false} \
  CONFIG.Output_Data_Width {16} \
  CONFIG.Output_Depth {16} \
  CONFIG.Output_Register_Type {Embedded_Reg} \
  CONFIG.Overflow_Flag {false} \
  CONFIG.Overflow_Flag_AXI {false} \
  CONFIG.Overflow_Sense {Active_High} \
  CONFIG.Overflow_Sense_AXI {Active_High} \
  CONFIG.PROTOCOL {AXI4} \
  CONFIG.Performance_Options {Standard_FIFO} \
  CONFIG.Programmable_Empty_Type {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_axis {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_rach {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_rdch {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_wach {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_wdch {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_wrch {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Full_Type {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_axis {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_rach {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_rdch {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_wach {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_wdch {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_wrch {No_Programmable_Full_Threshold} \
  CONFIG.READ_CLK.FREQ_HZ {100000000} \
  CONFIG.READ_WRITE_MODE {READ_WRITE} \
  CONFIG.RUSER_Width {0} \
  CONFIG.Read_Clock_Frequency {1} \
  CONFIG.Read_Data_Count {false} \
  CONFIG.Read_Data_Count_Width {4} \
  CONFIG.Register_Slice_Mode_axis {Fully_Registered} \
  CONFIG.Register_Slice_Mode_rach {Fully_Registered} \
  CONFIG.Register_Slice_Mode_rdch {Fully_Registered} \
  CONFIG.Register_Slice_Mode_wach {Fully_Registered} \
  CONFIG.Register_Slice_Mode_wdch {Fully_Registered} \
  CONFIG.Register_Slice_Mode_wrch {Fully_Registered} \
  CONFIG.Reset_Pin {false} \
  CONFIG.Reset_Type {Asynchronous_Reset} \
  CONFIG.SLAVE_ACLK.FREQ_HZ {100000000} \
  CONFIG.Slave_interface_Clock_enable_memory_mapped {false} \
  CONFIG.TDATA_NUM_BYTES {1} \
  CONFIG.TDEST_WIDTH {0} \
  CONFIG.TID_WIDTH {0} \
  CONFIG.TKEEP_WIDTH {1} \
  CONFIG.TSTRB_WIDTH {1} \
  CONFIG.TUSER_WIDTH {4} \
  CONFIG.Underflow_Flag {false} \
  CONFIG.Underflow_Flag_AXI {false} \
  CONFIG.Underflow_Sense {Active_High} \
  CONFIG.Underflow_Sense_AXI {Active_High} \
  CONFIG.Use_Dout_Reset {false} \
  CONFIG.Use_Embedded_Registers {false} \
  CONFIG.Use_Embedded_Registers_axis {false} \
  CONFIG.Use_Extra_Logic {false} \
  CONFIG.Valid_Flag {true} \
  CONFIG.Valid_Sense {Active_High} \
  CONFIG.WRITE_CLK.FREQ_HZ {100000000} \
  CONFIG.WUSER_Width {0} \
  CONFIG.Write_Acknowledge_Flag {false} \
  CONFIG.Write_Acknowledge_Sense {Active_High} \
  CONFIG.Write_Clock_Frequency {1} \
  CONFIG.Write_Data_Count {false} \
  CONFIG.Write_Data_Count_Width {4} \
  CONFIG.asymmetric_port_width {false} \
  CONFIG.axis_type {FIFO} \
  CONFIG.dynamic_power_saving {false} \
  CONFIG.ecc_pipeline_reg {false} \
  CONFIG.enable_low_latency {false} \
  CONFIG.enable_read_pointer_increment_by2 {false} \
  CONFIG.rach_type {FIFO} \
  CONFIG.rdch_type {FIFO} \
  CONFIG.synchronization_stages {4} \
  CONFIG.synchronization_stages_axi {2} \
  CONFIG.use_dout_register {false} \
  CONFIG.wach_type {FIFO} \
  CONFIG.wdch_type {FIFO} \
  CONFIG.wrch_type {FIFO} \
  ] [get_ips ${ip_name}]
set_property generate_synth_checkpoint 0 [get_files CDC_fifo_16b.xci]
#  fifo_generator  

#  fifo_generator Properties definition 
set ip_name CDC_fifo_1b
create_ip -name fifo_generator -vendor xilinx.com -library ip -module_name ${ip_name}
set_property -dict [list \
  CONFIG.ADDRESS_WIDTH {32} \
  CONFIG.ARUSER_Width {0} \
  CONFIG.AWUSER_Width {0} \
  CONFIG.Add_NGC_Constraint_AXI {false} \
  CONFIG.Almost_Empty_Flag {false} \
  CONFIG.Almost_Full_Flag {false} \
  CONFIG.BUSER_Width {0} \
  CONFIG.CORE_CLK.FREQ_HZ {100000000} \
  CONFIG.C_SELECT_XPM {0} \
  CONFIG.Clock_Enable_Type {Slave_Interface_Clock_Enable} \
  CONFIG.Clock_Type_AXI {Common_Clock} \
  CONFIG.Component_Name {CDC_fifo_1b} \
  CONFIG.DATA_WIDTH {64} \
  CONFIG.Data_Count {false} \
  CONFIG.Data_Count_Width {4} \
  CONFIG.Disable_Timing_Violations {false} \
  CONFIG.Disable_Timing_Violations_AXI {false} \
  CONFIG.Dout_Reset_Value {0} \
  CONFIG.Empty_Threshold_Assert_Value {2} \
  CONFIG.Empty_Threshold_Assert_Value_axis {1022} \
  CONFIG.Empty_Threshold_Assert_Value_rach {1022} \
  CONFIG.Empty_Threshold_Assert_Value_rdch {1022} \
  CONFIG.Empty_Threshold_Assert_Value_wach {1022} \
  CONFIG.Empty_Threshold_Assert_Value_wdch {1022} \
  CONFIG.Empty_Threshold_Assert_Value_wrch {1022} \
  CONFIG.Empty_Threshold_Negate_Value {3} \
  CONFIG.Enable_Common_Overflow {false} \
  CONFIG.Enable_Common_Underflow {false} \
  CONFIG.Enable_Data_Counts_axis {false} \
  CONFIG.Enable_Data_Counts_rach {false} \
  CONFIG.Enable_Data_Counts_rdch {false} \
  CONFIG.Enable_Data_Counts_wach {false} \
  CONFIG.Enable_Data_Counts_wdch {false} \
  CONFIG.Enable_Data_Counts_wrch {false} \
  CONFIG.Enable_ECC {false} \
  CONFIG.Enable_ECC_Type {Hard_ECC} \
  CONFIG.Enable_ECC_axis {false} \
  CONFIG.Enable_ECC_rach {false} \
  CONFIG.Enable_ECC_rdch {false} \
  CONFIG.Enable_ECC_wach {false} \
  CONFIG.Enable_ECC_wdch {false} \
  CONFIG.Enable_ECC_wrch {false} \
  CONFIG.Enable_Reset_Synchronization {true} \
  CONFIG.Enable_Safety_Circuit {false} \
  CONFIG.Enable_TLAST {false} \
  CONFIG.Enable_TREADY {true} \
  CONFIG.FIFO_Application_Type_axis {Data_FIFO} \
  CONFIG.FIFO_Application_Type_rach {Data_FIFO} \
  CONFIG.FIFO_Application_Type_rdch {Data_FIFO} \
  CONFIG.FIFO_Application_Type_wach {Data_FIFO} \
  CONFIG.FIFO_Application_Type_wdch {Data_FIFO} \
  CONFIG.FIFO_Application_Type_wrch {Data_FIFO} \
  CONFIG.FIFO_Implementation_axis {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_rach {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_rdch {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_wach {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_wdch {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_wrch {Common_Clock_Block_RAM} \
  CONFIG.Fifo_Implementation {Independent_Clocks_Distributed_RAM} \
  CONFIG.Full_Flags_Reset_Value {0} \
  CONFIG.Full_Threshold_Assert_Value {13} \
  CONFIG.Full_Threshold_Assert_Value_axis {1023} \
  CONFIG.Full_Threshold_Assert_Value_rach {1023} \
  CONFIG.Full_Threshold_Assert_Value_rdch {1023} \
  CONFIG.Full_Threshold_Assert_Value_wach {1023} \
  CONFIG.Full_Threshold_Assert_Value_wdch {1023} \
  CONFIG.Full_Threshold_Assert_Value_wrch {1023} \
  CONFIG.Full_Threshold_Negate_Value {12} \
  CONFIG.HAS_ACLKEN {false} \
  CONFIG.HAS_TKEEP {false} \
  CONFIG.HAS_TSTRB {false} \
  CONFIG.ID_WIDTH {0} \
  CONFIG.INTERFACE_TYPE {Native} \
  CONFIG.Inject_Dbit_Error {false} \
  CONFIG.Inject_Dbit_Error_axis {false} \
  CONFIG.Inject_Dbit_Error_rach {false} \
  CONFIG.Inject_Dbit_Error_rdch {false} \
  CONFIG.Inject_Dbit_Error_wach {false} \
  CONFIG.Inject_Dbit_Error_wdch {false} \
  CONFIG.Inject_Dbit_Error_wrch {false} \
  CONFIG.Inject_Sbit_Error {false} \
  CONFIG.Inject_Sbit_Error_axis {false} \
  CONFIG.Inject_Sbit_Error_rach {false} \
  CONFIG.Inject_Sbit_Error_rdch {false} \
  CONFIG.Inject_Sbit_Error_wach {false} \
  CONFIG.Inject_Sbit_Error_wdch {false} \
  CONFIG.Inject_Sbit_Error_wrch {false} \
  CONFIG.Input_Data_Width {1} \
  CONFIG.Input_Depth {16} \
  CONFIG.Input_Depth_axis {1024} \
  CONFIG.Input_Depth_rach {16} \
  CONFIG.Input_Depth_rdch {1024} \
  CONFIG.Input_Depth_wach {16} \
  CONFIG.Input_Depth_wdch {1024} \
  CONFIG.Input_Depth_wrch {16} \
  CONFIG.MASTER_ACLK.FREQ_HZ {100000000} \
  CONFIG.Master_interface_Clock_enable_memory_mapped {false} \
  CONFIG.Output_Data_Width {1} \
  CONFIG.Output_Depth {16} \
  CONFIG.Output_Register_Type {Embedded_Reg} \
  CONFIG.Overflow_Flag {false} \
  CONFIG.Overflow_Flag_AXI {false} \
  CONFIG.Overflow_Sense {Active_High} \
  CONFIG.Overflow_Sense_AXI {Active_High} \
  CONFIG.PROTOCOL {AXI4} \
  CONFIG.Performance_Options {Standard_FIFO} \
  CONFIG.Programmable_Empty_Type {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_axis {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_rach {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_rdch {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_wach {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_wdch {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_wrch {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Full_Type {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_axis {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_rach {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_rdch {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_wach {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_wdch {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_wrch {No_Programmable_Full_Threshold} \
  CONFIG.READ_CLK.FREQ_HZ {100000000} \
  CONFIG.READ_WRITE_MODE {READ_WRITE} \
  CONFIG.RUSER_Width {0} \
  CONFIG.Read_Clock_Frequency {1} \
  CONFIG.Read_Data_Count {false} \
  CONFIG.Read_Data_Count_Width {4} \
  CONFIG.Register_Slice_Mode_axis {Fully_Registered} \
  CONFIG.Register_Slice_Mode_rach {Fully_Registered} \
  CONFIG.Register_Slice_Mode_rdch {Fully_Registered} \
  CONFIG.Register_Slice_Mode_wach {Fully_Registered} \
  CONFIG.Register_Slice_Mode_wdch {Fully_Registered} \
  CONFIG.Register_Slice_Mode_wrch {Fully_Registered} \
  CONFIG.Reset_Pin {false} \
  CONFIG.Reset_Type {Asynchronous_Reset} \
  CONFIG.SLAVE_ACLK.FREQ_HZ {100000000} \
  CONFIG.Slave_interface_Clock_enable_memory_mapped {false} \
  CONFIG.TDATA_NUM_BYTES {1} \
  CONFIG.TDEST_WIDTH {0} \
  CONFIG.TID_WIDTH {0} \
  CONFIG.TKEEP_WIDTH {1} \
  CONFIG.TSTRB_WIDTH {1} \
  CONFIG.TUSER_WIDTH {4} \
  CONFIG.Underflow_Flag {false} \
  CONFIG.Underflow_Flag_AXI {false} \
  CONFIG.Underflow_Sense {Active_High} \
  CONFIG.Underflow_Sense_AXI {Active_High} \
  CONFIG.Use_Dout_Reset {false} \
  CONFIG.Use_Embedded_Registers {false} \
  CONFIG.Use_Embedded_Registers_axis {false} \
  CONFIG.Use_Extra_Logic {false} \
  CONFIG.Valid_Flag {true} \
  CONFIG.Valid_Sense {Active_High} \
  CONFIG.WRITE_CLK.FREQ_HZ {100000000} \
  CONFIG.WUSER_Width {0} \
  CONFIG.Write_Acknowledge_Flag {false} \
  CONFIG.Write_Acknowledge_Sense {Active_High} \
  CONFIG.Write_Clock_Frequency {1} \
  CONFIG.Write_Data_Count {false} \
  CONFIG.Write_Data_Count_Width {4} \
  CONFIG.asymmetric_port_width {false} \
  CONFIG.axis_type {FIFO} \
  CONFIG.dynamic_power_saving {false} \
  CONFIG.ecc_pipeline_reg {false} \
  CONFIG.enable_low_latency {false} \
  CONFIG.enable_read_pointer_increment_by2 {false} \
  CONFIG.rach_type {FIFO} \
  CONFIG.rdch_type {FIFO} \
  CONFIG.synchronization_stages {4} \
  CONFIG.synchronization_stages_axi {2} \
  CONFIG.use_dout_register {false} \
  CONFIG.wach_type {FIFO} \
  CONFIG.wdch_type {FIFO} \
  CONFIG.wrch_type {FIFO} \
  ] [get_ips ${ip_name}]
set_property generate_synth_checkpoint 0 [get_files CDC_fifo_1b.xci]
#  fifo_generator  

#  fifo_generator Properties definition 
set ip_name CDC_fifo_3b
create_ip -name fifo_generator -vendor xilinx.com -library ip -module_name ${ip_name}
set_property -dict [list \
  CONFIG.ADDRESS_WIDTH {32} \
  CONFIG.ARUSER_Width {0} \
  CONFIG.AWUSER_Width {0} \
  CONFIG.Add_NGC_Constraint_AXI {false} \
  CONFIG.Almost_Empty_Flag {false} \
  CONFIG.Almost_Full_Flag {false} \
  CONFIG.BUSER_Width {0} \
  CONFIG.CORE_CLK.FREQ_HZ {100000000} \
  CONFIG.C_SELECT_XPM {0} \
  CONFIG.Clock_Enable_Type {Slave_Interface_Clock_Enable} \
  CONFIG.Clock_Type_AXI {Common_Clock} \
  CONFIG.Component_Name {CDC_fifo_3b} \
  CONFIG.DATA_WIDTH {64} \
  CONFIG.Data_Count {false} \
  CONFIG.Data_Count_Width {4} \
  CONFIG.Disable_Timing_Violations {false} \
  CONFIG.Disable_Timing_Violations_AXI {false} \
  CONFIG.Dout_Reset_Value {0} \
  CONFIG.Empty_Threshold_Assert_Value {2} \
  CONFIG.Empty_Threshold_Assert_Value_axis {1022} \
  CONFIG.Empty_Threshold_Assert_Value_rach {1022} \
  CONFIG.Empty_Threshold_Assert_Value_rdch {1022} \
  CONFIG.Empty_Threshold_Assert_Value_wach {1022} \
  CONFIG.Empty_Threshold_Assert_Value_wdch {1022} \
  CONFIG.Empty_Threshold_Assert_Value_wrch {1022} \
  CONFIG.Empty_Threshold_Negate_Value {3} \
  CONFIG.Enable_Common_Overflow {false} \
  CONFIG.Enable_Common_Underflow {false} \
  CONFIG.Enable_Data_Counts_axis {false} \
  CONFIG.Enable_Data_Counts_rach {false} \
  CONFIG.Enable_Data_Counts_rdch {false} \
  CONFIG.Enable_Data_Counts_wach {false} \
  CONFIG.Enable_Data_Counts_wdch {false} \
  CONFIG.Enable_Data_Counts_wrch {false} \
  CONFIG.Enable_ECC {false} \
  CONFIG.Enable_ECC_Type {Hard_ECC} \
  CONFIG.Enable_ECC_axis {false} \
  CONFIG.Enable_ECC_rach {false} \
  CONFIG.Enable_ECC_rdch {false} \
  CONFIG.Enable_ECC_wach {false} \
  CONFIG.Enable_ECC_wdch {false} \
  CONFIG.Enable_ECC_wrch {false} \
  CONFIG.Enable_Reset_Synchronization {true} \
  CONFIG.Enable_Safety_Circuit {false} \
  CONFIG.Enable_TLAST {false} \
  CONFIG.Enable_TREADY {true} \
  CONFIG.FIFO_Application_Type_axis {Data_FIFO} \
  CONFIG.FIFO_Application_Type_rach {Data_FIFO} \
  CONFIG.FIFO_Application_Type_rdch {Data_FIFO} \
  CONFIG.FIFO_Application_Type_wach {Data_FIFO} \
  CONFIG.FIFO_Application_Type_wdch {Data_FIFO} \
  CONFIG.FIFO_Application_Type_wrch {Data_FIFO} \
  CONFIG.FIFO_Implementation_axis {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_rach {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_rdch {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_wach {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_wdch {Common_Clock_Block_RAM} \
  CONFIG.FIFO_Implementation_wrch {Common_Clock_Block_RAM} \
  CONFIG.Fifo_Implementation {Independent_Clocks_Distributed_RAM} \
  CONFIG.Full_Flags_Reset_Value {0} \
  CONFIG.Full_Threshold_Assert_Value {13} \
  CONFIG.Full_Threshold_Assert_Value_axis {1023} \
  CONFIG.Full_Threshold_Assert_Value_rach {1023} \
  CONFIG.Full_Threshold_Assert_Value_rdch {1023} \
  CONFIG.Full_Threshold_Assert_Value_wach {1023} \
  CONFIG.Full_Threshold_Assert_Value_wdch {1023} \
  CONFIG.Full_Threshold_Assert_Value_wrch {1023} \
  CONFIG.Full_Threshold_Negate_Value {12} \
  CONFIG.HAS_ACLKEN {false} \
  CONFIG.HAS_TKEEP {false} \
  CONFIG.HAS_TSTRB {false} \
  CONFIG.ID_WIDTH {0} \
  CONFIG.INTERFACE_TYPE {Native} \
  CONFIG.Inject_Dbit_Error {false} \
  CONFIG.Inject_Dbit_Error_axis {false} \
  CONFIG.Inject_Dbit_Error_rach {false} \
  CONFIG.Inject_Dbit_Error_rdch {false} \
  CONFIG.Inject_Dbit_Error_wach {false} \
  CONFIG.Inject_Dbit_Error_wdch {false} \
  CONFIG.Inject_Dbit_Error_wrch {false} \
  CONFIG.Inject_Sbit_Error {false} \
  CONFIG.Inject_Sbit_Error_axis {false} \
  CONFIG.Inject_Sbit_Error_rach {false} \
  CONFIG.Inject_Sbit_Error_rdch {false} \
  CONFIG.Inject_Sbit_Error_wach {false} \
  CONFIG.Inject_Sbit_Error_wdch {false} \
  CONFIG.Inject_Sbit_Error_wrch {false} \
  CONFIG.Input_Data_Width {3} \
  CONFIG.Input_Depth {16} \
  CONFIG.Input_Depth_axis {1024} \
  CONFIG.Input_Depth_rach {16} \
  CONFIG.Input_Depth_rdch {1024} \
  CONFIG.Input_Depth_wach {16} \
  CONFIG.Input_Depth_wdch {1024} \
  CONFIG.Input_Depth_wrch {16} \
  CONFIG.MASTER_ACLK.FREQ_HZ {100000000} \
  CONFIG.Master_interface_Clock_enable_memory_mapped {false} \
  CONFIG.Output_Data_Width {3} \
  CONFIG.Output_Depth {16} \
  CONFIG.Output_Register_Type {Embedded_Reg} \
  CONFIG.Overflow_Flag {false} \
  CONFIG.Overflow_Flag_AXI {false} \
  CONFIG.Overflow_Sense {Active_High} \
  CONFIG.Overflow_Sense_AXI {Active_High} \
  CONFIG.PROTOCOL {AXI4} \
  CONFIG.Performance_Options {Standard_FIFO} \
  CONFIG.Programmable_Empty_Type {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_axis {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_rach {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_rdch {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_wach {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_wdch {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Empty_Type_wrch {No_Programmable_Empty_Threshold} \
  CONFIG.Programmable_Full_Type {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_axis {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_rach {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_rdch {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_wach {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_wdch {No_Programmable_Full_Threshold} \
  CONFIG.Programmable_Full_Type_wrch {No_Programmable_Full_Threshold} \
  CONFIG.READ_CLK.FREQ_HZ {100000000} \
  CONFIG.READ_WRITE_MODE {READ_WRITE} \
  CONFIG.RUSER_Width {0} \
  CONFIG.Read_Clock_Frequency {1} \
  CONFIG.Read_Data_Count {false} \
  CONFIG.Read_Data_Count_Width {4} \
  CONFIG.Register_Slice_Mode_axis {Fully_Registered} \
  CONFIG.Register_Slice_Mode_rach {Fully_Registered} \
  CONFIG.Register_Slice_Mode_rdch {Fully_Registered} \
  CONFIG.Register_Slice_Mode_wach {Fully_Registered} \
  CONFIG.Register_Slice_Mode_wdch {Fully_Registered} \
  CONFIG.Register_Slice_Mode_wrch {Fully_Registered} \
  CONFIG.Reset_Pin {false} \
  CONFIG.Reset_Type {Asynchronous_Reset} \
  CONFIG.SLAVE_ACLK.FREQ_HZ {100000000} \
  CONFIG.Slave_interface_Clock_enable_memory_mapped {false} \
  CONFIG.TDATA_NUM_BYTES {1} \
  CONFIG.TDEST_WIDTH {0} \
  CONFIG.TID_WIDTH {0} \
  CONFIG.TKEEP_WIDTH {1} \
  CONFIG.TSTRB_WIDTH {1} \
  CONFIG.TUSER_WIDTH {4} \
  CONFIG.Underflow_Flag {false} \
  CONFIG.Underflow_Flag_AXI {false} \
  CONFIG.Underflow_Sense {Active_High} \
  CONFIG.Underflow_Sense_AXI {Active_High} \
  CONFIG.Use_Dout_Reset {false} \
  CONFIG.Use_Embedded_Registers {false} \
  CONFIG.Use_Embedded_Registers_axis {false} \
  CONFIG.Use_Extra_Logic {false} \
  CONFIG.Valid_Flag {true} \
  CONFIG.Valid_Sense {Active_High} \
  CONFIG.WRITE_CLK.FREQ_HZ {100000000} \
  CONFIG.WUSER_Width {0} \
  CONFIG.Write_Acknowledge_Flag {false} \
  CONFIG.Write_Acknowledge_Sense {Active_High} \
  CONFIG.Write_Clock_Frequency {1} \
  CONFIG.Write_Data_Count {false} \
  CONFIG.Write_Data_Count_Width {4} \
  CONFIG.asymmetric_port_width {false} \
  CONFIG.axis_type {FIFO} \
  CONFIG.dynamic_power_saving {false} \
  CONFIG.ecc_pipeline_reg {false} \
  CONFIG.enable_low_latency {false} \
  CONFIG.enable_read_pointer_increment_by2 {false} \
  CONFIG.rach_type {FIFO} \
  CONFIG.rdch_type {FIFO} \
  CONFIG.synchronization_stages {4} \
  CONFIG.synchronization_stages_axi {2} \
  CONFIG.use_dout_register {false} \
  CONFIG.wach_type {FIFO} \
  CONFIG.wdch_type {FIFO} \
  CONFIG.wrch_type {FIFO} \
  ] [get_ips ${ip_name}]
set_property generate_synth_checkpoint 0 [get_files CDC_fifo_3b.xci]
#  fifo_generator  

#  fir_compiler Properties definition 
set ip_name adc_decimation_1536msps_to_768msps
create_ip -name fir_compiler -vendor xilinx.com -library ip -module_name ${ip_name}
set_property -dict [list \
  CONFIG.ACLK_INTF.FREQ_HZ {100000000} \
  CONFIG.BestPrecision {false} \
  CONFIG.Blank_Output {false} \
  CONFIG.Channel_Sequence {Basic} \
  CONFIG.Clock_Frequency {245.76} \
  CONFIG.CoefficientSource {COE_File} \
  CONFIG.CoefficientVector {6,0,-4,-3,5,6,-6,-13,7,44,64,44,7,-13,-6,6,5,-3,-4,0,6} \
  CONFIG.Coefficient_Buffer_Type {Automatic} \
  CONFIG.Coefficient_File $script_path/../../RTL_code/coe_files/rfdc_adc_data_decim_and_depack/lowpass_common_decimation_filter.coe \
  CONFIG.Coefficient_Fractional_Bits {0} \
  CONFIG.Coefficient_Reload {false} \
  CONFIG.Coefficient_Sets {1} \
  CONFIG.Coefficient_Sign {Signed} \
  CONFIG.Coefficient_Structure {Inferred} \
  CONFIG.Coefficient_Width {16} \
  CONFIG.ColumnConfig {1} \
  CONFIG.Component_Name {adc_decimation_1536msps_to_768msps} \
  CONFIG.DATA_Has_TLAST {Not_Required} \
  CONFIG.DATA_TUSER_Width {1} \
  CONFIG.Data_Buffer_Type {Automatic} \
  CONFIG.Data_Fractional_Bits {0} \
  CONFIG.Data_Sign {Signed} \
  CONFIG.Data_Width {16} \
  CONFIG.Decimation_Rate {2} \
  CONFIG.DisplayReloadOrder {false} \
  CONFIG.Filter_Architecture {Systolic_Multiply_Accumulate} \
  CONFIG.Filter_Selection {1} \
  CONFIG.Filter_Type {Decimation} \
  CONFIG.GUI_Behaviour {Coregen} \
  CONFIG.Gen_MIF_Files {false} \
  CONFIG.Gen_MIF_from_COE {false} \
  CONFIG.Gen_MIF_from_Spec {false} \
  CONFIG.HardwareOversamplingRate {1} \
  CONFIG.Has_ACLKEN {false} \
  CONFIG.Has_ARESETn {true} \
  CONFIG.Input_Buffer_Type {Automatic} \
  CONFIG.Inter_Column_Pipe_Length {4} \
  CONFIG.Interpolation_Rate {1} \
  CONFIG.M_DATA_Has_TREADY {false} \
  CONFIG.M_DATA_Has_TUSER {Not_Required} \
  CONFIG.Multi_Column_Support {Automatic} \
  CONFIG.Num_Reload_Slots {1} \
  CONFIG.Number_Channels {1} \
  CONFIG.Number_Paths {1} \
  CONFIG.Optimization_Goal {Area} \
  CONFIG.Optimization_List {None} \
  CONFIG.Optimization_Selection {None} \
  CONFIG.Output_Buffer_Type {Automatic} \
  CONFIG.Output_Rounding_Mode {Full_Precision} \
  CONFIG.Output_Width {33} \
  CONFIG.Passband_Max {0.5} \
  CONFIG.Passband_Min {0.0} \
  CONFIG.Pattern_List {P4-0,P4-1,P4-2,P4-3,P4-4} \
  CONFIG.Preference_For_Other_Storage {Automatic} \
  CONFIG.Quantization {Integer_Coefficients} \
  CONFIG.RateSpecification {Frequency_Specification} \
  CONFIG.Rate_Change_Type {Integer} \
  CONFIG.Reload_File {no_coe_file_loaded} \
  CONFIG.Reset_Data_Vector {true} \
  CONFIG.S_CONFIG_Method {Single} \
  CONFIG.S_CONFIG_Sync_Mode {On_Vector} \
  CONFIG.S_DATA_Has_FIFO {true} \
  CONFIG.S_DATA_Has_TUSER {Not_Required} \
  CONFIG.SamplePeriod {1} \
  CONFIG.Sample_Frequency {15.36} \
  CONFIG.Select_Pattern {All} \
  CONFIG.Stopband_Max {1.0} \
  CONFIG.Stopband_Min {0.5} \
  CONFIG.Zero_Pack_Factor {1} \
  ] [get_ips ${ip_name}]
set_property generate_synth_checkpoint 0 [get_files adc_decimation_1536msps_to_768msps.xci]
#  fir_compiler  

#  fir_compiler Properties definition 
set ip_name adc_decimation_24576msps_to_3072msps
create_ip -name fir_compiler -vendor xilinx.com -library ip -module_name ${ip_name}
set_property -dict [list \
  CONFIG.ACLK_INTF.FREQ_HZ {100000000} \
  CONFIG.BestPrecision {false} \
  CONFIG.Blank_Output {false} \
  CONFIG.Channel_Sequence {Basic} \
  CONFIG.Clock_Frequency {245.76} \
  CONFIG.CoefficientSource {COE_File} \
  CONFIG.CoefficientVector {6,0,-4,-3,5,6,-6,-13,7,44,64,44,7,-13,-6,6,5,-3,-4,0,6} \
  CONFIG.Coefficient_Buffer_Type {Automatic} \
  CONFIG.Coefficient_File $script_path/../../RTL_code/coe_files/rfdc_adc_data_decim_and_depack/lowpass_common_decimation_filter.coe \
  CONFIG.Coefficient_Fractional_Bits {0} \
  CONFIG.Coefficient_Reload {false} \
  CONFIG.Coefficient_Sets {1} \
  CONFIG.Coefficient_Sign {Signed} \
  CONFIG.Coefficient_Structure {Inferred} \
  CONFIG.Coefficient_Width {16} \
  CONFIG.ColumnConfig {3} \
  CONFIG.Component_Name {adc_decimation_24576msps_to_3072msps} \
  CONFIG.DATA_Has_TLAST {Not_Required} \
  CONFIG.DATA_TUSER_Width {1} \
  CONFIG.Data_Buffer_Type {Automatic} \
  CONFIG.Data_Fractional_Bits {0} \
  CONFIG.Data_Sign {Signed} \
  CONFIG.Data_Width {16} \
  CONFIG.Decimation_Rate {8} \
  CONFIG.DisplayReloadOrder {false} \
  CONFIG.Filter_Architecture {Systolic_Multiply_Accumulate} \
  CONFIG.Filter_Selection {1} \
  CONFIG.Filter_Type {Decimation} \
  CONFIG.GUI_Behaviour {Coregen} \
  CONFIG.Gen_MIF_Files {false} \
  CONFIG.Gen_MIF_from_COE {false} \
  CONFIG.Gen_MIF_from_Spec {false} \
  CONFIG.HardwareOversamplingRate {1} \
  CONFIG.Has_ACLKEN {false} \
  CONFIG.Has_ARESETn {true} \
  CONFIG.Input_Buffer_Type {Automatic} \
  CONFIG.Inter_Column_Pipe_Length {4} \
  CONFIG.Interpolation_Rate {1} \
  CONFIG.M_DATA_Has_TREADY {false} \
  CONFIG.M_DATA_Has_TUSER {Not_Required} \
  CONFIG.Multi_Column_Support {Automatic} \
  CONFIG.Num_Reload_Slots {1} \
  CONFIG.Number_Channels {1} \
  CONFIG.Number_Paths {1} \
  CONFIG.Optimization_Goal {Area} \
  CONFIG.Optimization_List {None} \
  CONFIG.Optimization_Selection {None} \
  CONFIG.Output_Buffer_Type {Automatic} \
  CONFIG.Output_Rounding_Mode {Full_Precision} \
  CONFIG.Output_Width {33} \
  CONFIG.Passband_Max {0.5} \
  CONFIG.Passband_Min {0.0} \
  CONFIG.Pattern_List {P4-0,P4-1,P4-2,P4-3,P4-4} \
  CONFIG.Preference_For_Other_Storage {Automatic} \
  CONFIG.Quantization {Integer_Coefficients} \
  CONFIG.RateSpecification {Frequency_Specification} \
  CONFIG.Rate_Change_Type {Integer} \
  CONFIG.Reload_File {no_coe_file_loaded} \
  CONFIG.Reset_Data_Vector {true} \
  CONFIG.S_CONFIG_Method {Single} \
  CONFIG.S_CONFIG_Sync_Mode {On_Vector} \
  CONFIG.S_DATA_Has_FIFO {true} \
  CONFIG.S_DATA_Has_TUSER {Not_Required} \
  CONFIG.SamplePeriod {1} \
  CONFIG.Sample_Frequency {245.76} \
  CONFIG.Select_Pattern {All} \
  CONFIG.Stopband_Max {1.0} \
  CONFIG.Stopband_Min {0.5} \
  CONFIG.Zero_Pack_Factor {1} \
  ] [get_ips ${ip_name}]
set_property generate_synth_checkpoint 0 [get_files adc_decimation_24576msps_to_3072msps.xci]
#  fir_compiler  

#  fir_compiler Properties definition 
set ip_name adc_decimation_3072msps_to_1536msps
create_ip -name fir_compiler -vendor xilinx.com -library ip -module_name ${ip_name}
set_property -dict [list \
  CONFIG.ACLK_INTF.FREQ_HZ {100000000} \
  CONFIG.BestPrecision {false} \
  CONFIG.Blank_Output {false} \
  CONFIG.Channel_Sequence {Basic} \
  CONFIG.Clock_Frequency {245.76} \
  CONFIG.CoefficientSource {COE_File} \
  CONFIG.CoefficientVector {6,0,-4,-3,5,6,-6,-13,7,44,64,44,7,-13,-6,6,5,-3,-4,0,6} \
  CONFIG.Coefficient_Buffer_Type {Automatic} \
  CONFIG.Coefficient_File $script_path/../../RTL_code/coe_files/rfdc_adc_data_decim_and_depack/lowpass_common_decimation_filter.coe \
  CONFIG.Coefficient_Fractional_Bits {0} \
  CONFIG.Coefficient_Reload {false} \
  CONFIG.Coefficient_Sets {1} \
  CONFIG.Coefficient_Sign {Signed} \
  CONFIG.Coefficient_Structure {Inferred} \
  CONFIG.Coefficient_Width {16} \
  CONFIG.ColumnConfig {2} \
  CONFIG.Component_Name {adc_decimation_3072msps_to_1536msps} \
  CONFIG.DATA_Has_TLAST {Not_Required} \
  CONFIG.DATA_TUSER_Width {1} \
  CONFIG.Data_Buffer_Type {Automatic} \
  CONFIG.Data_Fractional_Bits {0} \
  CONFIG.Data_Sign {Signed} \
  CONFIG.Data_Width {16} \
  CONFIG.Decimation_Rate {2} \
  CONFIG.DisplayReloadOrder {false} \
  CONFIG.Filter_Architecture {Systolic_Multiply_Accumulate} \
  CONFIG.Filter_Selection {1} \
  CONFIG.Filter_Type {Decimation} \
  CONFIG.GUI_Behaviour {Coregen} \
  CONFIG.Gen_MIF_Files {false} \
  CONFIG.Gen_MIF_from_COE {false} \
  CONFIG.Gen_MIF_from_Spec {false} \
  CONFIG.HardwareOversamplingRate {1} \
  CONFIG.Has_ACLKEN {false} \
  CONFIG.Has_ARESETn {true} \
  CONFIG.Input_Buffer_Type {Automatic} \
  CONFIG.Inter_Column_Pipe_Length {4} \
  CONFIG.Interpolation_Rate {1} \
  CONFIG.M_DATA_Has_TREADY {false} \
  CONFIG.M_DATA_Has_TUSER {Not_Required} \
  CONFIG.Multi_Column_Support {Automatic} \
  CONFIG.Num_Reload_Slots {1} \
  CONFIG.Number_Channels {1} \
  CONFIG.Number_Paths {1} \
  CONFIG.Optimization_Goal {Area} \
  CONFIG.Optimization_List {None} \
  CONFIG.Optimization_Selection {None} \
  CONFIG.Output_Buffer_Type {Automatic} \
  CONFIG.Output_Rounding_Mode {Full_Precision} \
  CONFIG.Output_Width {33} \
  CONFIG.Passband_Max {0.5} \
  CONFIG.Passband_Min {0.0} \
  CONFIG.Pattern_List {P4-0,P4-1,P4-2,P4-3,P4-4} \
  CONFIG.Preference_For_Other_Storage {Automatic} \
  CONFIG.Quantization {Integer_Coefficients} \
  CONFIG.RateSpecification {Frequency_Specification} \
  CONFIG.Rate_Change_Type {Integer} \
  CONFIG.Reload_File {no_coe_file_loaded} \
  CONFIG.Reset_Data_Vector {true} \
  CONFIG.S_CONFIG_Method {Single} \
  CONFIG.S_CONFIG_Sync_Mode {On_Vector} \
  CONFIG.S_DATA_Has_FIFO {true} \
  CONFIG.S_DATA_Has_TUSER {Not_Required} \
  CONFIG.SamplePeriod {1} \
  CONFIG.Sample_Frequency {30.72} \
  CONFIG.Select_Pattern {All} \
  CONFIG.Stopband_Max {1.0} \
  CONFIG.Stopband_Min {0.5} \
  CONFIG.Zero_Pack_Factor {1} \
  ] [get_ips ${ip_name}]
set_property generate_synth_checkpoint 0 [get_files adc_decimation_3072msps_to_1536msps.xci]
#  fir_compiler  

#  fir_compiler Properties definition 
set ip_name adc_decimation_384msps_to_192msps
create_ip -name fir_compiler -vendor xilinx.com -library ip -module_name ${ip_name}
set_property -dict [list \
  CONFIG.ACLK_INTF.FREQ_HZ {100000000} \
  CONFIG.BestPrecision {false} \
  CONFIG.Blank_Output {false} \
  CONFIG.Channel_Sequence {Basic} \
  CONFIG.Clock_Frequency {245.76} \
  CONFIG.CoefficientSource {COE_File} \
  CONFIG.CoefficientVector {6,0,-4,-3,5,6,-6,-13,7,44,64,44,7,-13,-6,6,5,-3,-4,0,6} \
  CONFIG.Coefficient_Buffer_Type {Automatic} \
  CONFIG.Coefficient_File $script_path/../../RTL_code/coe_files/rfdc_adc_data_decim_and_depack/lowpass_common_decimation_filter.coe \
  CONFIG.Coefficient_Fractional_Bits {0} \
  CONFIG.Coefficient_Reload {false} \
  CONFIG.Coefficient_Sets {1} \
  CONFIG.Coefficient_Sign {Signed} \
  CONFIG.Coefficient_Structure {Inferred} \
  CONFIG.Coefficient_Width {16} \
  CONFIG.ColumnConfig {1} \
  CONFIG.Component_Name {adc_decimation_384msps_to_192msps} \
  CONFIG.DATA_Has_TLAST {Not_Required} \
  CONFIG.DATA_TUSER_Width {1} \
  CONFIG.Data_Buffer_Type {Automatic} \
  CONFIG.Data_Fractional_Bits {0} \
  CONFIG.Data_Sign {Signed} \
  CONFIG.Data_Width {16} \
  CONFIG.Decimation_Rate {2} \
  CONFIG.DisplayReloadOrder {false} \
  CONFIG.Filter_Architecture {Systolic_Multiply_Accumulate} \
  CONFIG.Filter_Selection {1} \
  CONFIG.Filter_Type {Decimation} \
  CONFIG.GUI_Behaviour {Coregen} \
  CONFIG.Gen_MIF_Files {false} \
  CONFIG.Gen_MIF_from_COE {false} \
  CONFIG.Gen_MIF_from_Spec {false} \
  CONFIG.HardwareOversamplingRate {1} \
  CONFIG.Has_ACLKEN {false} \
  CONFIG.Has_ARESETn {true} \
  CONFIG.Input_Buffer_Type {Automatic} \
  CONFIG.Inter_Column_Pipe_Length {4} \
  CONFIG.Interpolation_Rate {1} \
  CONFIG.M_DATA_Has_TREADY {false} \
  CONFIG.M_DATA_Has_TUSER {Not_Required} \
  CONFIG.Multi_Column_Support {Automatic} \
  CONFIG.Num_Reload_Slots {1} \
  CONFIG.Number_Channels {1} \
  CONFIG.Number_Paths {1} \
  CONFIG.Optimization_Goal {Area} \
  CONFIG.Optimization_List {None} \
  CONFIG.Optimization_Selection {None} \
  CONFIG.Output_Buffer_Type {Automatic} \
  CONFIG.Output_Rounding_Mode {Full_Precision} \
  CONFIG.Output_Width {33} \
  CONFIG.Passband_Max {0.5} \
  CONFIG.Passband_Min {0.0} \
  CONFIG.Pattern_List {P4-0,P4-1,P4-2,P4-3,P4-4} \
  CONFIG.Preference_For_Other_Storage {Automatic} \
  CONFIG.Quantization {Integer_Coefficients} \
  CONFIG.RateSpecification {Frequency_Specification} \
  CONFIG.Rate_Change_Type {Integer} \
  CONFIG.Reload_File {no_coe_file_loaded} \
  CONFIG.Reset_Data_Vector {true} \
  CONFIG.S_CONFIG_Method {Single} \
  CONFIG.S_CONFIG_Sync_Mode {On_Vector} \
  CONFIG.S_DATA_Has_FIFO {true} \
  CONFIG.S_DATA_Has_TUSER {Not_Required} \
  CONFIG.SamplePeriod {1} \
  CONFIG.Sample_Frequency {3.84} \
  CONFIG.Select_Pattern {All} \
  CONFIG.Stopband_Max {1.0} \
  CONFIG.Stopband_Min {0.5} \
  CONFIG.Zero_Pack_Factor {1} \
  ] [get_ips ${ip_name}]
set_property generate_synth_checkpoint 0 [get_files adc_decimation_384msps_to_192msps.xci]
#  fir_compiler  

#  fir_compiler Properties definition 
set ip_name adc_decimation_768msps_to_384msps
create_ip -name fir_compiler -vendor xilinx.com -library ip -module_name ${ip_name}
set_property -dict [list \
  CONFIG.ACLK_INTF.FREQ_HZ {100000000} \
  CONFIG.BestPrecision {false} \
  CONFIG.Blank_Output {false} \
  CONFIG.Channel_Sequence {Basic} \
  CONFIG.Clock_Frequency {245.76} \
  CONFIG.CoefficientSource {COE_File} \
  CONFIG.CoefficientVector {6,0,-4,-3,5,6,-6,-13,7,44,64,44,7,-13,-6,6,5,-3,-4,0,6} \
  CONFIG.Coefficient_Buffer_Type {Automatic} \
  CONFIG.Coefficient_File $script_path/../../RTL_code/coe_files/rfdc_adc_data_decim_and_depack/lowpass_common_decimation_filter.coe \
  CONFIG.Coefficient_Fractional_Bits {0} \
  CONFIG.Coefficient_Reload {false} \
  CONFIG.Coefficient_Sets {1} \
  CONFIG.Coefficient_Sign {Signed} \
  CONFIG.Coefficient_Structure {Inferred} \
  CONFIG.Coefficient_Width {16} \
  CONFIG.ColumnConfig {1} \
  CONFIG.Component_Name {adc_decimation_768msps_to_384msps} \
  CONFIG.DATA_Has_TLAST {Not_Required} \
  CONFIG.DATA_TUSER_Width {1} \
  CONFIG.Data_Buffer_Type {Automatic} \
  CONFIG.Data_Fractional_Bits {0} \
  CONFIG.Data_Sign {Signed} \
  CONFIG.Data_Width {16} \
  CONFIG.Decimation_Rate {2} \
  CONFIG.DisplayReloadOrder {false} \
  CONFIG.Filter_Architecture {Systolic_Multiply_Accumulate} \
  CONFIG.Filter_Selection {1} \
  CONFIG.Filter_Type {Decimation} \
  CONFIG.GUI_Behaviour {Coregen} \
  CONFIG.Gen_MIF_Files {false} \
  CONFIG.Gen_MIF_from_COE {false} \
  CONFIG.Gen_MIF_from_Spec {false} \
  CONFIG.HardwareOversamplingRate {1} \
  CONFIG.Has_ACLKEN {false} \
  CONFIG.Has_ARESETn {true} \
  CONFIG.Input_Buffer_Type {Automatic} \
  CONFIG.Inter_Column_Pipe_Length {4} \
  CONFIG.Interpolation_Rate {1} \
  CONFIG.M_DATA_Has_TREADY {false} \
  CONFIG.M_DATA_Has_TUSER {Not_Required} \
  CONFIG.Multi_Column_Support {Automatic} \
  CONFIG.Num_Reload_Slots {1} \
  CONFIG.Number_Channels {1} \
  CONFIG.Number_Paths {1} \
  CONFIG.Optimization_Goal {Area} \
  CONFIG.Optimization_List {None} \
  CONFIG.Optimization_Selection {None} \
  CONFIG.Output_Buffer_Type {Automatic} \
  CONFIG.Output_Rounding_Mode {Full_Precision} \
  CONFIG.Output_Width {33} \
  CONFIG.Passband_Max {0.5} \
  CONFIG.Passband_Min {0.0} \
  CONFIG.Pattern_List {P4-0,P4-1,P4-2,P4-3,P4-4} \
  CONFIG.Preference_For_Other_Storage {Automatic} \
  CONFIG.Quantization {Integer_Coefficients} \
  CONFIG.RateSpecification {Frequency_Specification} \
  CONFIG.Rate_Change_Type {Integer} \
  CONFIG.Reload_File {no_coe_file_loaded} \
  CONFIG.Reset_Data_Vector {true} \
  CONFIG.S_CONFIG_Method {Single} \
  CONFIG.S_CONFIG_Sync_Mode {On_Vector} \
  CONFIG.S_DATA_Has_FIFO {true} \
  CONFIG.S_DATA_Has_TUSER {Not_Required} \
  CONFIG.SamplePeriod {1} \
  CONFIG.Sample_Frequency {7.68} \
  CONFIG.Select_Pattern {All} \
  CONFIG.Stopband_Max {1.0} \
  CONFIG.Stopband_Min {0.5} \
  CONFIG.Zero_Pack_Factor {1} \
  ] [get_ips ${ip_name}]
set_property generate_synth_checkpoint 0 [get_files adc_decimation_768msps_to_384msps.xci]
#  fir_compiler  


#  clk_wiz Properties definition 
set ip_name clk_wiz_0_ADC
create_ip -name clk_wiz -vendor xilinx.com -library ip -module_name ${ip_name}
set_property -dict [list \
  CONFIG.AUTO_PRIMITIVE MMCM \
  CONFIG.AXI_DRP false \
  CONFIG.CALC_DONE empty \
  CONFIG.CDDCDONE_PORT cddcdone \
  CONFIG.CDDCREQ_PORT cddcreq \
  CONFIG.CLKFB_IN_N_PORT clkfb_in_n \
  CONFIG.CLKFB_IN_PORT clkfb_in \
  CONFIG.CLKFB_IN_P_PORT clkfb_in_p \
  CONFIG.CLKFB_IN_SIGNALING SINGLE \
  CONFIG.CLKFB_OUT_N_PORT clkfb_out_n \
  CONFIG.CLKFB_OUT_PORT clkfb_out \
  CONFIG.CLKFB_OUT_P_PORT clkfb_out_p \
  CONFIG.CLKFB_STOPPED_PORT clkfb_stopped \
  CONFIG.CLKIN1_JITTER_PS 81.38 \
  CONFIG.CLKIN1_UI_JITTER 0.010 \
  CONFIG.CLKIN2_JITTER_PS 100.0 \
  CONFIG.CLKIN2_UI_JITTER 0.010 \
  CONFIG.CLKOUT1_DRIVES No_buffer \
  CONFIG.CLKOUT1_JITTER 107.858 \
  CONFIG.CLKOUT1_MATCHED_ROUTING false \
  CONFIG.CLKOUT1_PHASE_ERROR 85.536 \
  CONFIG.CLKOUT1_REQUESTED_DUTY_CYCLE 50.000 \
  CONFIG.CLKOUT1_REQUESTED_OUT_FREQ 122.88 \
  CONFIG.CLKOUT1_REQUESTED_PHASE 0.000 \
  CONFIG.CLKOUT1_SEQUENCE_NUMBER 1 \
  CONFIG.CLKOUT1_USED true \
  CONFIG.CLKOUT2_DRIVES No_buffer \
  CONFIG.CLKOUT2_JITTER 94.365 \
  CONFIG.CLKOUT2_MATCHED_ROUTING false \
  CONFIG.CLKOUT2_PHASE_ERROR 84.619 \
  CONFIG.CLKOUT2_REQUESTED_DUTY_CYCLE 50.000 \
  CONFIG.CLKOUT2_REQUESTED_OUT_FREQ 245.76 \
  CONFIG.CLKOUT2_REQUESTED_PHASE 0.000 \
  CONFIG.CLKOUT2_SEQUENCE_NUMBER 1 \
  CONFIG.CLKOUT2_USED false \
  CONFIG.CLKOUT3_DRIVES Buffer \
  CONFIG.CLKOUT3_JITTER 94.365 \
  CONFIG.CLKOUT3_MATCHED_ROUTING false \
  CONFIG.CLKOUT3_PHASE_ERROR 84.619 \
  CONFIG.CLKOUT3_REQUESTED_DUTY_CYCLE 50.000 \
  CONFIG.CLKOUT3_REQUESTED_OUT_FREQ 245.76 \
  CONFIG.CLKOUT3_REQUESTED_PHASE 0.000 \
  CONFIG.CLKOUT3_SEQUENCE_NUMBER 1 \
  CONFIG.CLKOUT3_USED false \
  CONFIG.CLKOUT4_DRIVES Buffer \
  CONFIG.CLKOUT4_JITTER 0.0 \
  CONFIG.CLKOUT4_MATCHED_ROUTING false \
  CONFIG.CLKOUT4_PHASE_ERROR 0.0 \
  CONFIG.CLKOUT4_REQUESTED_DUTY_CYCLE 50.000 \
  CONFIG.CLKOUT4_REQUESTED_OUT_FREQ 100.000 \
  CONFIG.CLKOUT4_REQUESTED_PHASE 0.000 \
  CONFIG.CLKOUT4_SEQUENCE_NUMBER 1 \
  CONFIG.CLKOUT4_USED false \
  CONFIG.CLKOUT5_DRIVES Buffer \
  CONFIG.CLKOUT5_JITTER 0.0 \
  CONFIG.CLKOUT5_MATCHED_ROUTING false \
  CONFIG.CLKOUT5_PHASE_ERROR 0.0 \
  CONFIG.CLKOUT5_REQUESTED_DUTY_CYCLE 50.000 \
  CONFIG.CLKOUT5_REQUESTED_OUT_FREQ 100.000 \
  CONFIG.CLKOUT5_REQUESTED_PHASE 0.000 \
  CONFIG.CLKOUT5_SEQUENCE_NUMBER 1 \
  CONFIG.CLKOUT5_USED false \
  CONFIG.CLKOUT6_DRIVES Buffer \
  CONFIG.CLKOUT6_JITTER 0.0 \
  CONFIG.CLKOUT6_MATCHED_ROUTING false \
  CONFIG.CLKOUT6_PHASE_ERROR 0.0 \
  CONFIG.CLKOUT6_REQUESTED_DUTY_CYCLE 50.000 \
  CONFIG.CLKOUT6_REQUESTED_OUT_FREQ 100.000 \
  CONFIG.CLKOUT6_REQUESTED_PHASE 0.000 \
  CONFIG.CLKOUT6_SEQUENCE_NUMBER 1 \
  CONFIG.CLKOUT6_USED false \
  CONFIG.CLKOUT7_DRIVES Buffer \
  CONFIG.CLKOUT7_JITTER 0.0 \
  CONFIG.CLKOUT7_MATCHED_ROUTING false \
  CONFIG.CLKOUT7_PHASE_ERROR 0.0 \
  CONFIG.CLKOUT7_REQUESTED_DUTY_CYCLE 50.000 \
  CONFIG.CLKOUT7_REQUESTED_OUT_FREQ 100.000 \
  CONFIG.CLKOUT7_REQUESTED_PHASE 0.000 \
  CONFIG.CLKOUT7_SEQUENCE_NUMBER 1 \
  CONFIG.CLKOUT7_USED false \
  CONFIG.CLKOUTPHY_REQUESTED_FREQ 600.000 \
  CONFIG.CLK_IN1_BOARD_INTERFACE Custom \
  CONFIG.CLK_IN2_BOARD_INTERFACE Custom \
  CONFIG.CLK_IN_SEL_PORT clk_in_sel \
  CONFIG.CLK_OUT1_PORT clk_out1 \
  CONFIG.CLK_OUT1_USE_FINE_PS_GUI false \
  CONFIG.CLK_OUT2_PORT clk_out2 \
  CONFIG.CLK_OUT2_USE_FINE_PS_GUI false \
  CONFIG.CLK_OUT3_PORT clk_out3 \
  CONFIG.CLK_OUT3_USE_FINE_PS_GUI false \
  CONFIG.CLK_OUT4_PORT clk_out4 \
  CONFIG.CLK_OUT4_USE_FINE_PS_GUI false \
  CONFIG.CLK_OUT5_PORT clk_out5 \
  CONFIG.CLK_OUT5_USE_FINE_PS_GUI false \
  CONFIG.CLK_OUT6_PORT clk_out6 \
  CONFIG.CLK_OUT6_USE_FINE_PS_GUI false \
  CONFIG.CLK_OUT7_PORT clk_out7 \
  CONFIG.CLK_OUT7_USE_FINE_PS_GUI false \
  CONFIG.CLK_VALID_PORT CLK_VALID \
  CONFIG.CLOCK_MGR_TYPE auto \
  CONFIG.Component_Name clk_wiz_0_ADC \
  CONFIG.DADDR_PORT daddr \
  CONFIG.DCLK_PORT dclk \
  CONFIG.DEN_PORT den \
  CONFIG.DIFF_CLK_IN1_BOARD_INTERFACE Custom \
  CONFIG.DIFF_CLK_IN2_BOARD_INTERFACE Custom \
  CONFIG.DIN_PORT din \
  CONFIG.DOUT_PORT dout \
  CONFIG.DRDY_PORT drdy \
  CONFIG.DWE_PORT dwe \
  CONFIG.ENABLE_CDDC false \
  CONFIG.ENABLE_CLKOUTPHY false \
  CONFIG.ENABLE_CLOCK_MONITOR false \
  CONFIG.ENABLE_USER_CLOCK0 false \
  CONFIG.ENABLE_USER_CLOCK1 false \
  CONFIG.ENABLE_USER_CLOCK2 false \
  CONFIG.ENABLE_USER_CLOCK3 false \
  CONFIG.Enable_PLL0 false \
  CONFIG.Enable_PLL1 false \
  CONFIG.FEEDBACK_SOURCE FDBK_ONCHIP \
  CONFIG.INPUT_CLK_STOPPED_PORT input_clk_stopped \
  CONFIG.INPUT_MODE frequency \
  CONFIG.INTERFACE_SELECTION Enable_AXI \
  CONFIG.IN_FREQ_UNITS Units_MHz \
  CONFIG.IN_JITTER_UNITS Units_UI \
  CONFIG.JITTER_OPTIONS UI \
  CONFIG.JITTER_SEL No_Jitter \
  CONFIG.LOCKED_PORT locked \
  CONFIG.MMCM_BANDWIDTH OPTIMIZED \
  CONFIG.MMCM_CLKFBOUT_MULT_F 9.750 \
  CONFIG.MMCM_CLKFBOUT_PHASE 0.000 \
  CONFIG.MMCM_CLKFBOUT_USE_FINE_PS false \
  CONFIG.MMCM_CLKIN1_PERIOD 8.138 \
  CONFIG.MMCM_CLKIN2_PERIOD 10.000 \
  CONFIG.MMCM_CLKOUT0_DIVIDE_F 9.750 \
  CONFIG.MMCM_CLKOUT0_DUTY_CYCLE 0.500 \
  CONFIG.MMCM_CLKOUT0_PHASE 0.000 \
  CONFIG.MMCM_CLKOUT0_USE_FINE_PS false \
  CONFIG.MMCM_CLKOUT1_DIVIDE 1 \
  CONFIG.MMCM_CLKOUT1_DUTY_CYCLE 0.500 \
  CONFIG.MMCM_CLKOUT1_PHASE 0.000 \
  CONFIG.MMCM_CLKOUT1_USE_FINE_PS false \
  CONFIG.MMCM_CLKOUT2_DIVIDE 1 \
  CONFIG.MMCM_CLKOUT2_DUTY_CYCLE 0.500 \
  CONFIG.MMCM_CLKOUT2_PHASE 0.000 \
  CONFIG.MMCM_CLKOUT2_USE_FINE_PS false \
  CONFIG.MMCM_CLKOUT3_DIVIDE 1 \
  CONFIG.MMCM_CLKOUT3_DUTY_CYCLE 0.500 \
  CONFIG.MMCM_CLKOUT3_PHASE 0.000 \
  CONFIG.MMCM_CLKOUT3_USE_FINE_PS false \
  CONFIG.MMCM_CLKOUT4_CASCADE false \
  CONFIG.MMCM_CLKOUT4_DIVIDE 1 \
  CONFIG.MMCM_CLKOUT4_DUTY_CYCLE 0.500 \
  CONFIG.MMCM_CLKOUT4_PHASE 0.000 \
  CONFIG.MMCM_CLKOUT4_USE_FINE_PS false \
  CONFIG.MMCM_CLKOUT5_DIVIDE 1 \
  CONFIG.MMCM_CLKOUT5_DUTY_CYCLE 0.500 \
  CONFIG.MMCM_CLKOUT5_PHASE 0.000 \
  CONFIG.MMCM_CLKOUT5_USE_FINE_PS false \
  CONFIG.MMCM_CLKOUT6_DIVIDE 1 \
  CONFIG.MMCM_CLKOUT6_DUTY_CYCLE 0.500 \
  CONFIG.MMCM_CLKOUT6_PHASE 0.000 \
  CONFIG.MMCM_CLKOUT6_USE_FINE_PS false \
  CONFIG.MMCM_CLOCK_HOLD false \
  CONFIG.MMCM_COMPENSATION AUTO \
  CONFIG.MMCM_DIVCLK_DIVIDE 1 \
  CONFIG.MMCM_NOTES None \
  CONFIG.MMCM_REF_JITTER1 0.010 \
  CONFIG.MMCM_REF_JITTER2 0.010 \
  CONFIG.MMCM_STARTUP_WAIT false \
  CONFIG.NUM_OUT_CLKS 1 \
  CONFIG.OVERRIDE_MMCM false \
  CONFIG.OVERRIDE_PLL false \
  CONFIG.PHASESHIFT_MODE LATENCY \
  CONFIG.PHASE_DUTY_CONFIG false \
  CONFIG.PLATFORM UNKNOWN \
  CONFIG.PLL_BANDWIDTH OPTIMIZED \
  CONFIG.PLL_CLKFBOUT_MULT 4 \
  CONFIG.PLL_CLKFBOUT_PHASE 0.000 \
  CONFIG.PLL_CLKIN_PERIOD 10.000 \
  CONFIG.PLL_CLKOUT0_DIVIDE 1 \
  CONFIG.PLL_CLKOUT0_DUTY_CYCLE 0.500 \
  CONFIG.PLL_CLKOUT0_PHASE 0.000 \
  CONFIG.PLL_CLKOUT1_DIVIDE 1 \
  CONFIG.PLL_CLKOUT1_DUTY_CYCLE 0.500 \
  CONFIG.PLL_CLKOUT1_PHASE 0.000 \
  CONFIG.PLL_CLKOUT2_DIVIDE 1 \
  CONFIG.PLL_CLKOUT2_DUTY_CYCLE 0.500 \
  CONFIG.PLL_CLKOUT2_PHASE 0.000 \
  CONFIG.PLL_CLKOUT3_DIVIDE 1 \
  CONFIG.PLL_CLKOUT3_DUTY_CYCLE 0.500 \
  CONFIG.PLL_CLKOUT3_PHASE 0.000 \
  CONFIG.PLL_CLKOUT4_DIVIDE 1 \
  CONFIG.PLL_CLKOUT4_DUTY_CYCLE 0.500 \
  CONFIG.PLL_CLKOUT4_PHASE 0.000 \
  CONFIG.PLL_CLKOUT5_DIVIDE 1 \
  CONFIG.PLL_CLKOUT5_DUTY_CYCLE 0.500 \
  CONFIG.PLL_CLKOUT5_PHASE 0.000 \
  CONFIG.PLL_CLK_FEEDBACK CLKFBOUT \
  CONFIG.PLL_COMPENSATION SYSTEM_SYNCHRONOUS \
  CONFIG.PLL_DIVCLK_DIVIDE 1 \
  CONFIG.PLL_NOTES None \
  CONFIG.PLL_REF_JITTER 0.010 \
  CONFIG.POWER_DOWN_PORT power_down \
  CONFIG.PRECISION 1 \
  CONFIG.PRIMARY_PORT clk_in1 \
  CONFIG.PRIMITIVE MMCM \
  CONFIG.PRIMTYPE_SEL mmcm_adv \
  CONFIG.PRIM_IN_FREQ 122.88 \
  CONFIG.PRIM_IN_JITTER 0.010 \
  CONFIG.PRIM_IN_TIMEPERIOD 10.000 \
  CONFIG.PRIM_SOURCE Global_buffer \
  CONFIG.PSCLK_PORT psclk \
  CONFIG.PSDONE_PORT psdone \
  CONFIG.PSEN_PORT psen \
  CONFIG.PSINCDEC_PORT psincdec \
  CONFIG.REF_CLK_FREQ 100.0 \
  CONFIG.RELATIVE_INCLK REL_PRIMARY \
  CONFIG.RESET_BOARD_INTERFACE Custom \
  CONFIG.RESET_PORT reset \
  CONFIG.RESET_TYPE ACTIVE_HIGH \
  CONFIG.SECONDARY_IN_FREQ 100.000 \
  CONFIG.SECONDARY_IN_JITTER 0.010 \
  CONFIG.SECONDARY_IN_TIMEPERIOD 10.000 \
  CONFIG.SECONDARY_PORT clk_in2 \
  CONFIG.SECONDARY_SOURCE Single_ended_clock_capable_pin \
  CONFIG.SS_MODE CENTER_HIGH \
  CONFIG.SS_MOD_FREQ 250 \
  CONFIG.SS_MOD_TIME 0.004 \
  CONFIG.STATUS_PORT STATUS \
  CONFIG.SUMMARY_STRINGS empty \
  CONFIG.USER_CLK_FREQ0 100.0 \
  CONFIG.USER_CLK_FREQ1 100.0 \
  CONFIG.USER_CLK_FREQ2 100.0 \
  CONFIG.USER_CLK_FREQ3 100.0 \
  CONFIG.USE_BOARD_FLOW false \
  CONFIG.USE_CLKFB_STOPPED false \
  CONFIG.USE_CLK_VALID false \
  CONFIG.USE_CLOCK_SEQUENCING false \
  CONFIG.USE_DYN_PHASE_SHIFT false \
  CONFIG.USE_DYN_RECONFIG true \
  CONFIG.USE_FREEZE false \
  CONFIG.USE_FREQ_SYNTH true \
  CONFIG.USE_INCLK_STOPPED false \
  CONFIG.USE_INCLK_SWITCHOVER false \
  CONFIG.USE_LOCKED true \
  CONFIG.USE_MAX_I_JITTER false \
  CONFIG.USE_MIN_O_JITTER false \
  CONFIG.USE_MIN_POWER false \
  CONFIG.USE_PHASE_ALIGNMENT false \
  CONFIG.USE_POWER_DOWN false \
  CONFIG.USE_RESET true \
  CONFIG.USE_SAFE_CLOCK_STARTUP false \
  CONFIG.USE_SPREAD_SPECTRUM false \
  CONFIG.USE_STATUS false \
  ] [get_ips ${ip_name}]
set_property generate_synth_checkpoint 0 [get_files clk_wiz_0_ADC.xci]
#  clk_wiz  

#  proc_sys_reset Properties definition 
set ip_name proc_sys_reset_synchronizer
create_ip -name proc_sys_reset -vendor xilinx.com -library ip -module_name ${ip_name}
set_property -dict [list \
  CONFIG.C_AUX_RESET_HIGH {0} \
  CONFIG.C_AUX_RST_WIDTH {4} \
  CONFIG.C_EXT_RESET_HIGH {0} \
  CONFIG.C_EXT_RST_WIDTH {4} \
  CONFIG.C_NUM_BUS_RST {1} \
  CONFIG.C_NUM_INTERCONNECT_ARESETN {1} \
  CONFIG.C_NUM_PERP_ARESETN {1} \
  CONFIG.C_NUM_PERP_RST {1} \
  CONFIG.Component_Name {proc_sys_reset_synchronizer} \
  CONFIG.RESET_BOARD_INTERFACE {Custom} \
  CONFIG.USE_BOARD_FLOW {false} \
  ] [get_ips ${ip_name}]
set_property generate_synth_checkpoint 0 [get_files proc_sys_reset_synchronizer.xci]
#  proc_sys_reset  
